-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_178_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln176_2 : IN STD_LOGIC_VECTOR (25 downto 0);
    zext_ln178 : IN STD_LOGIC_VECTOR (2 downto 0);
    fc1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    fc1_ce0 : OUT STD_LOGIC;
    fc1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    sum_11_out : OUT STD_LOGIC_VECTOR (25 downto 0);
    sum_11_out_ap_vld : OUT STD_LOGIC;
    grp_fu_724_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_724_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_724_p_ce : OUT STD_LOGIC );
end;


architecture behav of cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_178_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_A : STD_LOGIC_VECTOR (11 downto 0) := "000000001010";
    constant ap_const_lv11_7F6 : STD_LOGIC_VECTOR (10 downto 0) := "11111110110";
    constant ap_const_lv11_A : STD_LOGIC_VECTOR (10 downto 0) := "00000001010";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln178_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal dense_1_param_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal dense_1_param_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_3_reg_520 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_3_reg_520_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln178_reg_525 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln178_reg_525_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln178_reg_525_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln178_reg_525_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln178_reg_525_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge4_i9_fu_454_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge4_i9_reg_539 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_exit_pp0_iter5_stage0 : STD_LOGIC;
    signal zext_ln180_1_fu_220_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln178_1_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_fu_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_497_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln176_2_cast_fu_157_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sum_10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_100 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln178_fu_180_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal dense_1_param_0_ce0_local : STD_LOGIC;
    signal fc1_ce0_local : STD_LOGIC;
    signal trunc_ln30_fu_186_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln30_fu_198_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl_fu_190_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln30_fu_204_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln30_fu_208_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln178_cast_fu_153_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal wi_fu_214_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal bitcast_ln726_13_fu_234_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_62_fu_250_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln180_1_fu_262_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln180_3_cast_fu_266_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln180_3_fu_274_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_fu_242_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln180_fu_278_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal trunc_ln180_fu_238_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln180_fu_258_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln180_1_fu_298_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln180_2_fu_304_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln180_1_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln180_fu_314_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln180_2_fu_320_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln180_fu_284_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln180_1_fu_326_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln180_2_fu_358_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln180_fu_362_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln180_3_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln180_4_fu_368_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln180_4_fu_350_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_237_fu_380_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln180_3_fu_340_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln180_1cast_fu_396_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln180_4_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln180_fu_400_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln180_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln180_2_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln180_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln180_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln180_1_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln180_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln180_1_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge4_i9_fu_454_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge4_i9_fu_454_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge4_i9_fu_454_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge4_i9_fu_454_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_497_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_497_p10 : STD_LOGIC_VECTOR (30 downto 0);
    signal storemerge4_i9_fu_454_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal storemerge4_i9_fu_454_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal storemerge4_i9_fu_454_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal storemerge4_i9_fu_454_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component cnn_gesture_top_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component cnn_gesture_top_sparsemux_9_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component cnn_gesture_top_mac_muladd_16s_15ns_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_178_2_dense_1_param_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component cnn_gesture_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    dense_1_param_0_U : component cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_178_2_dense_1_param_0_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 768,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dense_1_param_0_address0,
        ce0 => dense_1_param_0_ce0_local,
        q0 => dense_1_param_0_q0);

    sparsemux_9_3_16_1_1_U398 : component cnn_gesture_top_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 16,
        CASE1 => "010",
        din1_WIDTH => 16,
        CASE2 => "001",
        din2_WIDTH => 16,
        CASE3 => "000",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_0,
        din1 => trunc_ln180_3_fu_340_p1,
        din2 => storemerge4_i9_fu_454_p6,
        din3 => storemerge4_i9_fu_454_p8,
        def => storemerge4_i9_fu_454_p9,
        sel => storemerge4_i9_fu_454_p10,
        dout => storemerge4_i9_fu_454_p11);

    mac_muladd_16s_15ns_32s_32_4_1_U399 : component cnn_gesture_top_mac_muladd_16s_15ns_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => storemerge4_i9_reg_539,
        din1 => grp_fu_497_p1,
        din2 => ap_sig_allocacmp_sum_10,
        ce => ap_const_logic_1,
        dout => grp_fu_497_p3);

    flow_control_loop_pipe_sequential_init_U : component cnn_gesture_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter5_stage0)) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    i_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln178_fu_174_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_100 <= add_ln178_fu_180_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_100 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    sum_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    sum_fu_96 <= sext_ln176_2_cast_fu_157_p1;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    sum_fu_96 <= grp_fu_497_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_3_reg_520 <= ap_sig_allocacmp_i_3;
                i_3_reg_520_pp0_iter1_reg <= i_3_reg_520;
                icmp_ln178_reg_525 <= icmp_ln178_fu_174_p2;
                icmp_ln178_reg_525_pp0_iter1_reg <= icmp_ln178_reg_525;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                icmp_ln178_reg_525_pp0_iter2_reg <= icmp_ln178_reg_525_pp0_iter1_reg;
                icmp_ln178_reg_525_pp0_iter3_reg <= icmp_ln178_reg_525_pp0_iter2_reg;
                icmp_ln178_reg_525_pp0_iter4_reg <= icmp_ln178_reg_525_pp0_iter3_reg;
                storemerge4_i9_reg_539 <= storemerge4_i9_fu_454_p11;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln178_fu_180_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv8_1));
    add_ln180_fu_314_p2 <= std_logic_vector(unsigned(trunc_ln180_2_fu_304_p1) + unsigned(ap_const_lv11_7F6));
    and_ln180_1_fu_438_p2 <= (xor_ln180_1_fu_432_p2 and icmp_ln180_1_fu_308_p2);
    and_ln180_fu_420_p2 <= (xor_ln180_fu_414_p2 and icmp_ln180_2_fu_334_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln178_fu_174_p2)
    begin
        if (((icmp_ln178_fu_174_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter5_stage0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone, icmp_ln178_reg_525_pp0_iter4_reg)
    begin
        if (((icmp_ln178_reg_525_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter5_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_100)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_100;
        end if; 
    end process;


    ap_sig_allocacmp_sum_10_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0, sum_fu_96, grp_fu_497_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ap_sig_allocacmp_sum_10 <= grp_fu_497_p3;
        else 
            ap_sig_allocacmp_sum_10 <= sum_fu_96;
        end if; 
    end process;

    ashr_ln180_fu_362_p2 <= std_logic_vector(shift_right(signed(select_ln180_fu_284_p3),to_integer(unsigned('0' & zext_ln180_2_fu_358_p1(31-1 downto 0)))));
    bitcast_ln726_13_fu_234_p1 <= grp_fu_724_p_dout0;
    dense_1_param_0_address0 <= zext_ln180_1_fu_220_p1(10 - 1 downto 0);

    dense_1_param_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dense_1_param_0_ce0_local <= ap_const_logic_1;
        else 
            dense_1_param_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fc1_address0 <= zext_ln178_1_fu_230_p1(7 - 1 downto 0);
    fc1_ce0 <= fc1_ce0_local;

    fc1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            fc1_ce0_local <= ap_const_logic_1;
        else 
            fc1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_497_p1 <= grp_fu_497_p10(15 - 1 downto 0);
    grp_fu_497_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(fc1_q0),31));
    grp_fu_724_p_ce <= ap_const_logic_1;
    grp_fu_724_p_din0 <= dense_1_param_0_q0;
    icmp_ln178_fu_174_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv8_80) else "0";
    icmp_ln180_1_fu_308_p2 <= "1" when (signed(sub_ln180_1_fu_298_p2) > signed(ap_const_lv12_A)) else "0";
    icmp_ln180_2_fu_334_p2 <= "1" when (sub_ln180_1_fu_298_p2 = ap_const_lv12_A) else "0";
    icmp_ln180_3_fu_344_p2 <= "1" when (unsigned(select_ln180_1_fu_326_p3) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln180_4_fu_390_p2 <= "1" when (tmp_237_fu_380_p4 = ap_const_lv7_0) else "0";
    icmp_ln180_fu_292_p2 <= "1" when (trunc_ln180_fu_238_p1 = ap_const_lv63_0) else "0";
    or_ln180_fu_426_p2 <= (icmp_ln180_fu_292_p2 or icmp_ln180_2_fu_334_p2);
    p_shl_fu_190_p3 <= (trunc_ln30_fu_186_p1 & ap_const_lv3_0);
    select_ln180_1_fu_326_p3 <= 
        add_ln180_fu_314_p2 when (icmp_ln180_1_fu_308_p2(0) = '1') else 
        sub_ln180_2_fu_320_p2;
    select_ln180_1cast_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln180_1_fu_326_p3),16));
    select_ln180_4_fu_350_p3 <= 
        ap_const_lv16_FFFF when (tmp_fu_242_p3(0) = '1') else 
        ap_const_lv16_0;
    select_ln180_fu_284_p3 <= 
        sub_ln180_fu_278_p2 when (tmp_fu_242_p3(0) = '1') else 
        zext_ln180_3_fu_274_p1;
        sext_ln176_2_cast_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln176_2),32));

    shl_ln180_fu_400_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln180_3_fu_340_p1),to_integer(unsigned('0' & select_ln180_1cast_fu_396_p1(16-1 downto 0)))));
    shl_ln30_fu_198_p2 <= std_logic_vector(shift_left(unsigned(ap_sig_allocacmp_i_3),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    storemerge4_i9_fu_454_p10 <= ((icmp_ln180_fu_292_p2 & and_ln180_fu_420_p2) & and_ln180_1_fu_438_p2);
    storemerge4_i9_fu_454_p6 <= 
        trunc_ln180_4_fu_368_p1 when (icmp_ln180_3_fu_344_p2(0) = '1') else 
        select_ln180_4_fu_350_p3;
    storemerge4_i9_fu_454_p8 <= 
        shl_ln180_fu_400_p2 when (icmp_ln180_4_fu_390_p2(0) = '1') else 
        ap_const_lv16_0;
    storemerge4_i9_fu_454_p9 <= "XXXXXXXXXXXXXXXX";
    sub_ln180_1_fu_298_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln180_fu_258_p1));
    sub_ln180_2_fu_320_p2 <= std_logic_vector(unsigned(ap_const_lv11_A) - unsigned(trunc_ln180_2_fu_304_p1));
    sub_ln180_fu_278_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln180_3_fu_274_p1));
    sub_ln30_fu_208_p2 <= std_logic_vector(unsigned(p_shl_fu_190_p3) - unsigned(zext_ln30_fu_204_p1));
    sum_11_out <= ap_sig_allocacmp_sum_10(26 - 1 downto 0);

    sum_11_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln178_reg_525_pp0_iter4_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((icmp_ln178_reg_525_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            sum_11_out_ap_vld <= ap_const_logic_1;
        else 
            sum_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_237_fu_380_p4 <= select_ln180_1_fu_326_p3(10 downto 4);
    tmp_62_fu_250_p3 <= bitcast_ln726_13_fu_234_p1(62 downto 52);
    tmp_fu_242_p3 <= bitcast_ln726_13_fu_234_p1(63 downto 63);
    trunc_ln180_1_fu_262_p1 <= bitcast_ln726_13_fu_234_p1(52 - 1 downto 0);
    trunc_ln180_2_fu_304_p1 <= sub_ln180_1_fu_298_p2(11 - 1 downto 0);
    trunc_ln180_3_fu_340_p1 <= select_ln180_fu_284_p3(16 - 1 downto 0);
    trunc_ln180_4_fu_368_p1 <= ashr_ln180_fu_362_p2(16 - 1 downto 0);
    trunc_ln180_fu_238_p1 <= bitcast_ln726_13_fu_234_p1(63 - 1 downto 0);
    trunc_ln30_fu_186_p1 <= ap_sig_allocacmp_i_3(7 - 1 downto 0);
    wi_fu_214_p2 <= std_logic_vector(unsigned(sub_ln30_fu_208_p2) + unsigned(zext_ln178_cast_fu_153_p1));
    xor_ln180_1_fu_432_p2 <= (or_ln180_fu_426_p2 xor ap_const_lv1_1);
    xor_ln180_fu_414_p2 <= (icmp_ln180_fu_292_p2 xor ap_const_lv1_1);
    zext_ln178_1_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_reg_520_pp0_iter1_reg),64));
    zext_ln178_cast_fu_153_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln178),10));
    zext_ln180_1_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(wi_fu_214_p2),64));
    zext_ln180_2_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln180_1_fu_326_p3),54));
    zext_ln180_3_cast_fu_266_p3 <= (ap_const_lv1_1 & trunc_ln180_1_fu_262_p1);
    zext_ln180_3_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln180_3_cast_fu_266_p3),54));
    zext_ln180_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_62_fu_250_p3),12));
    zext_ln30_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln30_fu_198_p2),10));
end behav;
