-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_g8j is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_g8j is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100111011100010010010101", 1 => "00111110010100001001010000101100", 2 => "00111101001000101110110100101011", 3 => "00111101101010111101000000011110", 
    4 => "00111101101100001000100010001100", 5 => "00111101001100010011011011100110", 6 => "00111101000101110000100100000010", 7 => "00111101100010111100001011110100", 
    8 => "00111110000000100001110000110000", 9 => "00111101100110101000011010010010", 10 => "00111101011100000000110100000011", 11 => "00111101000001100011000100100111", 
    12 => "00111101100001011011101001110011", 13 => "00111101110000001001011000011000", 14 => "00111101001100110101100101100111", 15 => "00111101100010011110101010100100", 
    16 => "00111101101111100111110000101101", 17 => "00111101101010011100000100110010", 18 => "00111101100001100110101101000001", 19 => "00111100110000111010010110000010", 
    20 => "00111101011011011010010010011011", 21 => "00111101101110110100100100001111", 22 => "00111101011111110110101011110101", 23 => "00111101001000011000010110011110", 
    24 => "00111101101111011011100100011100", 25 => "00111101000110110101011100111111", 26 => "00111101001011000100111101101110", 27 => "00111101100010101111011011111010", 
    28 => "00111101000110100000010111110000", 29 => "00111101100010010111100100100110", 30 => "00111101010111101110000101011110", 31 => "00111101010010111111011111011011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

