-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_197_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    logits_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    logits_ce0 : OUT STD_LOGIC;
    logits_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln198 : IN STD_LOGIC_VECTOR (15 downto 0);
    max_v_1_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    exps_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    exps_ce0 : OUT STD_LOGIC;
    exps_we0 : OUT STD_LOGIC;
    exps_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    sum_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    sum_7_out_ap_vld : OUT STD_LOGIC;
    grp_fu_724_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_724_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_724_p_ce : OUT STD_LOGIC );
end;


architecture behav of cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_197_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_A : STD_LOGIC_VECTOR (11 downto 0) := "000000001010";
    constant ap_const_lv11_7F6 : STD_LOGIC_VECTOR (10 downto 0) := "11111110110";
    constant ap_const_lv11_A : STD_LOGIC_VECTOR (10 downto 0) := "00000001010";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln197_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln198_cast_fu_186_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln198_cast_reg_660 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln197_reg_665 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln197_reg_665_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln197_fu_215_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln197_reg_669_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln198_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln198_reg_679 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_243_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_684 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln198_fu_257_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln198_reg_689 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_1_fu_277_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln198_1_reg_694 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln198_fu_281_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln198_reg_699 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_180_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal storemerge4_i_fu_599_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge4_i_reg_714 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sum_7_fu_124 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sum_fu_626_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal i_1_fu_128 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln197_fu_209_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal logits_ce0_local : STD_LOGIC;
    signal exps_we0_local : STD_LOGIC;
    signal exps_ce0_local : STD_LOGIC;
    signal grp_fu_180_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln198_1_fu_225_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln198_1_fu_225_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln198_fu_229_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln198_fu_238_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln198_fu_234_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln198_1_fu_251_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_50_fu_269_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_50_fu_269_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln198_1_fu_287_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal zext_ln198_2_fu_290_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal shl_ln198_fu_293_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal lshr_ln3_fu_299_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_234_fu_313_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln198_2_fu_329_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln198_2_fu_334_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln198_1_fu_321_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln198_1_fu_338_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln198_4_fu_309_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_52_fu_344_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pi_assign_fu_351_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_fu_363_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln768_fu_367_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln726_17_fu_379_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_60_fu_395_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln198_3_fu_407_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln198_6_cast_fu_411_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln198_6_fu_419_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_235_fu_387_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln198_3_fu_423_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal trunc_ln198_2_fu_383_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln198_3_fu_403_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln198_4_fu_443_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln198_4_fu_449_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln198_2_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln198_2_fu_459_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln198_5_fu_465_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln198_2_fu_429_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln198_3_fu_471_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln198_5_fu_503_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln198_fu_507_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln198_4_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln198_6_fu_513_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln198_6_fu_495_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_236_fu_525_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln198_5_fu_485_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln198_3cast_fu_541_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln198_5_fu_535_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln198_1_fu_545_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln198_1_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln198_3_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln198_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln198_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln198_1_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln198_1_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge4_i_fu_599_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge4_i_fu_599_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge4_i_fu_599_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge4_i_fu_599_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_50_fu_269_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_50_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge4_i_fu_599_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal storemerge4_i_fu_599_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal storemerge4_i_fu_599_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal storemerge4_i_fu_599_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component cnn_gesture_top_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component cnn_gesture_top_fexp_32ns_32ns_32_8_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component cnn_gesture_top_ctlz_17_17_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (16 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component cnn_gesture_top_sparsemux_9_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component cnn_gesture_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fexp_32ns_32ns_32_8_full_dsp_1_U410 : component cnn_gesture_top_fexp_32ns_32ns_32_8_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 8,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_0,
        din1 => grp_fu_180_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_180_p2);

    ctlz_17_17_1_1_U411 : component cnn_gesture_top_ctlz_17_17_1_1
    generic map (
        din_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        din => tmp_50_fu_269_p1,
        dout => tmp_50_fu_269_p3);

    sparsemux_9_3_16_1_1_U412 : component cnn_gesture_top_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 16,
        CASE1 => "010",
        din1_WIDTH => 16,
        CASE2 => "001",
        din2_WIDTH => 16,
        CASE3 => "000",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_0,
        din1 => trunc_ln198_5_fu_485_p1,
        din2 => storemerge4_i_fu_599_p6,
        din3 => storemerge4_i_fu_599_p8,
        def => storemerge4_i_fu_599_p9,
        sel => storemerge4_i_fu_599_p10,
        dout => storemerge4_i_fu_599_p11);

    flow_control_loop_pipe_sequential_init_U : component cnn_gesture_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln197_fu_203_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_1_fu_128 <= add_ln197_fu_209_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_128 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    sum_7_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    sum_7_fu_124 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter11 = ap_const_logic_1)) then 
                    sum_7_fu_124 <= sum_fu_626_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln198_reg_699 <= add_ln198_fu_281_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln197_reg_665 <= icmp_ln197_fu_203_p2;
                icmp_ln197_reg_665_pp0_iter1_reg <= icmp_ln197_reg_665;
                icmp_ln198_reg_679 <= icmp_ln198_fu_238_p2;
                select_ln198_reg_689 <= select_ln198_fu_257_p3;
                sext_ln198_cast_reg_660 <= sext_ln198_cast_fu_186_p1;
                tmp_reg_684 <= sub_ln198_fu_229_p2(16 downto 16);
                trunc_ln198_1_reg_694 <= trunc_ln198_1_fu_277_p1;
                    zext_ln197_reg_669(2 downto 0) <= zext_ln197_fu_215_p1(2 downto 0);
                    zext_ln197_reg_669_pp0_iter1_reg(2 downto 0) <= zext_ln197_reg_669(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln197_reg_665_pp0_iter2_reg <= icmp_ln197_reg_665_pp0_iter1_reg;
                icmp_ln197_reg_665_pp0_iter3_reg <= icmp_ln197_reg_665_pp0_iter2_reg;
                icmp_ln197_reg_665_pp0_iter4_reg <= icmp_ln197_reg_665_pp0_iter3_reg;
                icmp_ln197_reg_665_pp0_iter5_reg <= icmp_ln197_reg_665_pp0_iter4_reg;
                icmp_ln197_reg_665_pp0_iter6_reg <= icmp_ln197_reg_665_pp0_iter5_reg;
                icmp_ln197_reg_665_pp0_iter7_reg <= icmp_ln197_reg_665_pp0_iter6_reg;
                icmp_ln197_reg_665_pp0_iter8_reg <= icmp_ln197_reg_665_pp0_iter7_reg;
                icmp_ln197_reg_665_pp0_iter9_reg <= icmp_ln197_reg_665_pp0_iter8_reg;
                storemerge4_i_reg_714 <= storemerge4_i_fu_599_p11;
                    zext_ln197_reg_669_pp0_iter10_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter9_reg(2 downto 0);
                    zext_ln197_reg_669_pp0_iter2_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter1_reg(2 downto 0);
                    zext_ln197_reg_669_pp0_iter3_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter2_reg(2 downto 0);
                    zext_ln197_reg_669_pp0_iter4_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter3_reg(2 downto 0);
                    zext_ln197_reg_669_pp0_iter5_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter4_reg(2 downto 0);
                    zext_ln197_reg_669_pp0_iter6_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter5_reg(2 downto 0);
                    zext_ln197_reg_669_pp0_iter7_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter6_reg(2 downto 0);
                    zext_ln197_reg_669_pp0_iter8_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter7_reg(2 downto 0);
                    zext_ln197_reg_669_pp0_iter9_reg(2 downto 0) <= zext_ln197_reg_669_pp0_iter8_reg(2 downto 0);
            end if;
        end if;
    end process;
    zext_ln197_reg_669(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter1_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter2_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter3_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter4_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter5_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter6_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter7_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter8_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter9_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln197_reg_669_pp0_iter10_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    LD_fu_363_p1 <= pi_assign_fu_351_p5(32 - 1 downto 0);
    add_ln197_fu_209_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv3_1));
    add_ln198_1_fu_338_p2 <= std_logic_vector(signed(sext_ln198_2_fu_334_p1) + signed(select_ln198_1_fu_321_p3));
    add_ln198_2_fu_459_p2 <= std_logic_vector(unsigned(trunc_ln198_4_fu_449_p1) + unsigned(ap_const_lv11_7F6));
    add_ln198_fu_281_p2 <= std_logic_vector(unsigned(trunc_ln198_1_fu_277_p1) + unsigned(ap_const_lv5_8));
    and_ln198_1_fu_583_p2 <= (xor_ln198_1_fu_577_p2 and icmp_ln198_2_fu_453_p2);
    and_ln198_fu_565_p2 <= (xor_ln198_fu_559_p2 and icmp_ln198_3_fu_479_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln197_fu_203_p2)
    begin
        if (((icmp_ln197_fu_203_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter10_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_1_fu_128)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i <= i_1_fu_128;
        end if; 
    end process;

    ashr_ln198_fu_507_p2 <= std_logic_vector(shift_right(signed(select_ln198_2_fu_429_p3),to_integer(unsigned('0' & zext_ln198_5_fu_503_p1(31-1 downto 0)))));
    bitcast_ln726_17_fu_379_p1 <= grp_fu_724_p_dout0;
    bitcast_ln768_fu_367_p1 <= LD_fu_363_p1;
    exps_address0 <= zext_ln197_reg_669_pp0_iter10_reg(3 - 1 downto 0);
    exps_ce0 <= exps_ce0_local;

    exps_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            exps_ce0_local <= ap_const_logic_1;
        else 
            exps_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    exps_d0 <= storemerge4_i_reg_714;
    exps_we0 <= exps_we0_local;

    exps_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            exps_we0_local <= ap_const_logic_1;
        else 
            exps_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_180_p1 <= 
        ap_const_lv32_0 when (icmp_ln198_reg_679(0) = '1') else 
        bitcast_ln768_fu_367_p1;
    grp_fu_724_p_ce <= ap_const_logic_1;
    grp_fu_724_p_din0 <= grp_fu_180_p2;
    icmp_ln197_fu_203_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv3_6) else "0";
    icmp_ln198_1_fu_437_p2 <= "1" when (trunc_ln198_2_fu_383_p1 = ap_const_lv63_0) else "0";
    icmp_ln198_2_fu_453_p2 <= "1" when (signed(sub_ln198_4_fu_443_p2) > signed(ap_const_lv12_A)) else "0";
    icmp_ln198_3_fu_479_p2 <= "1" when (sub_ln198_4_fu_443_p2 = ap_const_lv12_A) else "0";
    icmp_ln198_4_fu_489_p2 <= "1" when (unsigned(select_ln198_3_fu_471_p3) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln198_5_fu_535_p2 <= "1" when (tmp_236_fu_525_p4 = ap_const_lv7_0) else "0";
    icmp_ln198_fu_238_p0 <= logits_q0;
    icmp_ln198_fu_238_p2 <= "1" when (icmp_ln198_fu_238_p0 = max_v_1_reload) else "0";
    logits_address0 <= zext_ln197_fu_215_p1(3 - 1 downto 0);
    logits_ce0 <= logits_ce0_local;

    logits_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            logits_ce0_local <= ap_const_logic_1;
        else 
            logits_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln3_fu_299_p4 <= shl_ln198_fu_293_p2(40 downto 1);
    or_ln198_fu_571_p2 <= (icmp_ln198_3_fu_479_p2 or icmp_ln198_1_fu_437_p2);
    pi_assign_fu_351_p5 <= (zext_ln198_4_fu_309_p1(63 downto 32) & tmp_52_fu_344_p3 & zext_ln198_4_fu_309_p1(22 downto 0));
    select_ln198_1_fu_321_p3 <= 
        ap_const_lv8_7F when (tmp_234_fu_313_p3(0) = '1') else 
        ap_const_lv8_7E;
    select_ln198_2_fu_429_p3 <= 
        sub_ln198_3_fu_423_p2 when (tmp_235_fu_387_p3(0) = '1') else 
        zext_ln198_6_fu_419_p1;
    select_ln198_3_fu_471_p3 <= 
        add_ln198_2_fu_459_p2 when (icmp_ln198_2_fu_453_p2(0) = '1') else 
        sub_ln198_5_fu_465_p2;
    select_ln198_3cast_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln198_3_fu_471_p3),16));
    select_ln198_6_fu_495_p3 <= 
        ap_const_lv16_FFFF when (tmp_235_fu_387_p3(0) = '1') else 
        ap_const_lv16_0;
    select_ln198_fu_257_p3 <= 
        sub_ln198_1_fu_251_p2 when (tmp_fu_243_p3(0) = '1') else 
        trunc_ln198_fu_234_p1;
    sext_ln198_1_fu_225_p0 <= logits_q0;
        sext_ln198_1_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln198_1_fu_225_p0),17));

        sext_ln198_2_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln198_2_fu_329_p2),8));

        sext_ln198_cast_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln198),17));

    shl_ln198_1_fu_545_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln198_5_fu_485_p1),to_integer(unsigned('0' & select_ln198_3cast_fu_541_p1(16-1 downto 0)))));
    shl_ln198_fu_293_p2 <= std_logic_vector(shift_left(unsigned(zext_ln198_1_fu_287_p1),to_integer(unsigned('0' & zext_ln198_2_fu_290_p1(31-1 downto 0)))));
    storemerge4_i_fu_599_p10 <= ((icmp_ln198_1_fu_437_p2 & and_ln198_fu_565_p2) & and_ln198_1_fu_583_p2);
    storemerge4_i_fu_599_p6 <= 
        trunc_ln198_6_fu_513_p1 when (icmp_ln198_4_fu_489_p2(0) = '1') else 
        select_ln198_6_fu_495_p3;
    storemerge4_i_fu_599_p8 <= 
        shl_ln198_1_fu_545_p2 when (icmp_ln198_5_fu_535_p2(0) = '1') else 
        ap_const_lv16_0;
    storemerge4_i_fu_599_p9 <= "XXXXXXXXXXXXXXXX";
    sub_ln198_1_fu_251_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln198_fu_234_p1));
    sub_ln198_2_fu_329_p2 <= std_logic_vector(unsigned(ap_const_lv5_7) - unsigned(trunc_ln198_1_reg_694));
    sub_ln198_3_fu_423_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln198_6_fu_419_p1));
    sub_ln198_4_fu_443_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln198_3_fu_403_p1));
    sub_ln198_5_fu_465_p2 <= std_logic_vector(unsigned(ap_const_lv11_A) - unsigned(trunc_ln198_4_fu_449_p1));
    sub_ln198_fu_229_p2 <= std_logic_vector(signed(sext_ln198_1_fu_225_p1) - signed(sext_ln198_cast_reg_660));
    sum_7_out <= sum_7_fu_124;

    sum_7_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln197_reg_665_pp0_iter9_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (icmp_ln197_reg_665_pp0_iter9_reg = ap_const_lv1_1))) then 
            sum_7_out_ap_vld <= ap_const_logic_1;
        else 
            sum_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sum_fu_626_p2 <= std_logic_vector(unsigned(storemerge4_i_reg_714) + unsigned(sum_7_fu_124));
    tmp_234_fu_313_p3 <= shl_ln198_fu_293_p2(25 downto 25);
    tmp_235_fu_387_p3 <= bitcast_ln726_17_fu_379_p1(63 downto 63);
    tmp_236_fu_525_p4 <= select_ln198_3_fu_471_p3(10 downto 4);
    tmp_50_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln198_fu_257_p3),17));
    tmp_52_fu_344_p3 <= (tmp_reg_684 & add_ln198_1_fu_338_p2);
    tmp_60_fu_395_p3 <= bitcast_ln726_17_fu_379_p1(62 downto 52);
    tmp_fu_243_p3 <= sub_ln198_fu_229_p2(16 downto 16);
    trunc_ln198_1_fu_277_p1 <= tmp_50_fu_269_p3(5 - 1 downto 0);
    trunc_ln198_2_fu_383_p1 <= bitcast_ln726_17_fu_379_p1(63 - 1 downto 0);
    trunc_ln198_3_fu_407_p1 <= bitcast_ln726_17_fu_379_p1(52 - 1 downto 0);
    trunc_ln198_4_fu_449_p1 <= sub_ln198_4_fu_443_p2(11 - 1 downto 0);
    trunc_ln198_5_fu_485_p1 <= select_ln198_2_fu_429_p3(16 - 1 downto 0);
    trunc_ln198_6_fu_513_p1 <= ashr_ln198_fu_507_p2(16 - 1 downto 0);
    trunc_ln198_fu_234_p1 <= sub_ln198_fu_229_p2(16 - 1 downto 0);
    xor_ln198_1_fu_577_p2 <= (or_ln198_fu_571_p2 xor ap_const_lv1_1);
    xor_ln198_fu_559_p2 <= (icmp_ln198_1_fu_437_p2 xor ap_const_lv1_1);
    zext_ln197_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),64));
    zext_ln198_1_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln198_reg_689),41));
    zext_ln198_2_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln198_reg_699),41));
    zext_ln198_3_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_60_fu_395_p3),12));
    zext_ln198_4_fu_309_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln3_fu_299_p4),64));
    zext_ln198_5_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln198_3_fu_471_p3),54));
    zext_ln198_6_cast_fu_411_p3 <= (ap_const_lv1_1 & trunc_ln198_3_fu_407_p1);
    zext_ln198_6_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln198_6_cast_fu_411_p3),54));
end behav;
