// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_126_1_VITIS_LOOP_127_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv2_out_address0,
        conv2_out_ce0,
        conv2_out_q0,
        conv2_out_address1,
        conv2_out_ce1,
        conv2_out_q1,
        pool2_out_address0,
        pool2_out_ce0,
        pool2_out_we0,
        pool2_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] conv2_out_address0;
output   conv2_out_ce0;
input  [15:0] conv2_out_q0;
output  [11:0] conv2_out_address1;
output   conv2_out_ce1;
input  [15:0] conv2_out_q1;
output  [10:0] pool2_out_address0;
output   pool2_out_ce0;
output   pool2_out_we0;
output  [15:0] pool2_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln126_fu_114_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] add_ln130_fu_208_p2;
reg   [10:0] add_ln130_reg_288;
wire   [63:0] zext_ln128_fu_192_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln129_fu_203_p1;
wire   [63:0] zext_ln130_fu_235_p1;
reg   [6:0] f_fu_46;
wire   [6:0] add_ln127_fu_214_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_f_load;
reg   [4:0] t_fu_50;
wire   [4:0] select_ln126_1_fu_152_p3;
reg   [4:0] ap_sig_allocacmp_t_load;
reg   [10:0] indvar_flatten37_fu_54;
wire   [10:0] add_ln126_1_fu_120_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten37_load;
reg    conv2_out_ce1_local;
reg    conv2_out_ce0_local;
reg    pool2_out_we0_local;
wire   [15:0] select_ln130_fu_245_p3;
reg    pool2_out_ce0_local;
wire   [0:0] icmp_ln127_fu_138_p2;
wire   [4:0] add_ln126_fu_132_p2;
wire   [6:0] select_ln126_fu_144_p3;
wire   [11:0] tmp_171_fu_184_p3;
wire   [11:0] tmp_170_fu_168_p3;
wire   [11:0] zext_ln128_2_fu_180_p1;
wire   [11:0] add_ln129_fu_197_p2;
wire   [10:0] tmp_s_fu_160_p3;
wire   [10:0] zext_ln128_1_fu_176_p1;
wire   [0:0] icmp_ln130_fu_239_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 f_fu_46 = 7'd0;
#0 t_fu_50 = 5'd0;
#0 indvar_flatten37_fu_54 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_gesture_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            f_fu_46 <= add_ln127_fu_214_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            f_fu_46 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten37_fu_54 <= add_ln126_1_fu_120_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten37_fu_54 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_50 <= select_ln126_1_fu_152_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_50 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln130_reg_288 <= add_ln130_fu_208_p2;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_114_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_f_load = 7'd0;
    end else begin
        ap_sig_allocacmp_f_load = f_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten37_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten37_load = indvar_flatten37_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 5'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_ce0_local = 1'b1;
    end else begin
        conv2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_ce1_local = 1'b1;
    end else begin
        conv2_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool2_out_ce0_local = 1'b1;
    end else begin
        pool2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool2_out_we0_local = 1'b1;
    end else begin
        pool2_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln126_1_fu_120_p2 = (ap_sig_allocacmp_indvar_flatten37_load + 11'd1);

assign add_ln126_fu_132_p2 = (ap_sig_allocacmp_t_load + 5'd1);

assign add_ln127_fu_214_p2 = (select_ln126_fu_144_p3 + 7'd1);

assign add_ln129_fu_197_p2 = (tmp_170_fu_168_p3 + zext_ln128_2_fu_180_p1);

assign add_ln130_fu_208_p2 = (tmp_s_fu_160_p3 + zext_ln128_1_fu_176_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv2_out_address0 = zext_ln129_fu_203_p1;

assign conv2_out_address1 = zext_ln128_fu_192_p1;

assign conv2_out_ce0 = conv2_out_ce0_local;

assign conv2_out_ce1 = conv2_out_ce1_local;

assign icmp_ln126_fu_114_p2 = ((ap_sig_allocacmp_indvar_flatten37_load == 11'd1600) ? 1'b1 : 1'b0);

assign icmp_ln127_fu_138_p2 = ((ap_sig_allocacmp_f_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln130_fu_239_p2 = (($signed(conv2_out_q1) > $signed(conv2_out_q0)) ? 1'b1 : 1'b0);

assign pool2_out_address0 = zext_ln130_fu_235_p1;

assign pool2_out_ce0 = pool2_out_ce0_local;

assign pool2_out_d0 = select_ln130_fu_245_p3;

assign pool2_out_we0 = pool2_out_we0_local;

assign select_ln126_1_fu_152_p3 = ((icmp_ln127_fu_138_p2[0:0] == 1'b1) ? add_ln126_fu_132_p2 : ap_sig_allocacmp_t_load);

assign select_ln126_fu_144_p3 = ((icmp_ln127_fu_138_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_f_load);

assign select_ln130_fu_245_p3 = ((icmp_ln130_fu_239_p2[0:0] == 1'b1) ? conv2_out_q1 : conv2_out_q0);

assign tmp_170_fu_168_p3 = {{select_ln126_1_fu_152_p3}, {7'd64}};

assign tmp_171_fu_184_p3 = {{select_ln126_1_fu_152_p3}, {select_ln126_fu_144_p3}};

assign tmp_s_fu_160_p3 = {{select_ln126_1_fu_152_p3}, {6'd0}};

assign zext_ln128_1_fu_176_p1 = select_ln126_fu_144_p3;

assign zext_ln128_2_fu_180_p1 = select_ln126_fu_144_p3;

assign zext_ln128_fu_192_p1 = tmp_171_fu_184_p3;

assign zext_ln129_fu_203_p1 = add_ln129_fu_197_p2;

assign zext_ln130_fu_235_p1 = add_ln130_reg_288;

endmodule //cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_126_1_VITIS_LOOP_127_2
