// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cnn_gesture_top_cnn_gesture_top,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.220000,HLS_SYN_LAT=225730,HLS_SYN_TPT=none,HLS_SYN_MEM=984,HLS_SYN_DSP=0,HLS_SYN_FF=22611,HLS_SYN_LUT=65711,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_gesture_top (
        ap_clk,
        ap_rst_n,
        input_stream_TDATA,
        input_stream_TVALID,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TLAST,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] input_stream_TDATA;
input   input_stream_TVALID;
output   input_stream_TREADY;
input  [3:0] input_stream_TKEEP;
input  [3:0] input_stream_TSTRB;
input  [0:0] input_stream_TLAST;
output  [31:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [3:0] output_stream_TKEEP;
output  [3:0] output_stream_TSTRB;
output  [0:0] output_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [5:0] input_address0;
reg    input_ce0;
reg    input_we0;
wire   [15:0] input_q0;
reg   [5:0] input_1_address0;
reg    input_1_ce0;
reg    input_1_we0;
wire   [15:0] input_1_q0;
reg   [5:0] input_2_address0;
reg    input_2_ce0;
reg    input_2_we0;
wire   [15:0] input_2_q0;
reg   [5:0] input_3_address0;
reg    input_3_ce0;
reg    input_3_we0;
wire   [15:0] input_3_q0;
reg   [5:0] input_4_address0;
reg    input_4_ce0;
reg    input_4_we0;
wire   [15:0] input_4_q0;
reg   [5:0] input_5_address0;
reg    input_5_ce0;
reg    input_5_we0;
wire   [15:0] input_5_q0;
reg   [5:0] input_6_address0;
reg    input_6_ce0;
reg    input_6_we0;
wire   [15:0] input_6_q0;
reg   [5:0] input_7_address0;
reg    input_7_ce0;
reg    input_7_we0;
wire   [15:0] input_7_q0;
reg   [5:0] input_8_address0;
reg    input_8_ce0;
reg    input_8_we0;
wire   [15:0] input_8_q0;
reg   [5:0] input_9_address0;
reg    input_9_ce0;
reg    input_9_we0;
wire   [15:0] input_9_q0;
reg   [5:0] input_10_address0;
reg    input_10_ce0;
reg    input_10_we0;
wire   [15:0] input_10_q0;
reg   [5:0] input_11_address0;
reg    input_11_ce0;
reg    input_11_we0;
wire   [15:0] input_11_q0;
reg   [5:0] input_12_address0;
reg    input_12_ce0;
reg    input_12_we0;
wire   [15:0] input_12_q0;
reg   [5:0] input_13_address0;
reg    input_13_ce0;
reg    input_13_we0;
wire   [15:0] input_13_q0;
reg   [5:0] input_14_address0;
reg    input_14_ce0;
reg    input_14_we0;
wire   [15:0] input_14_q0;
reg   [5:0] input_15_address0;
reg    input_15_ce0;
reg    input_15_we0;
wire   [15:0] input_15_q0;
reg   [5:0] input_16_address0;
reg    input_16_ce0;
reg    input_16_we0;
wire   [15:0] input_16_q0;
reg   [5:0] input_17_address0;
reg    input_17_ce0;
reg    input_17_we0;
wire   [15:0] input_17_q0;
reg   [2:0] output_address0;
reg    output_ce0;
reg    output_we0;
wire   [15:0] output_q0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_done;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_idle;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_ready;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_d0;
wire   [5:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_ce0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_we0;
wire   [15:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_d0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_stream_TREADY;
wire   [31:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_grp_fu_462_p_din0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_grp_fu_462_p_ce;
wire    grp_cnn_gesture_core_fu_294_ap_start;
wire    grp_cnn_gesture_core_fu_294_ap_done;
wire    grp_cnn_gesture_core_fu_294_ap_idle;
wire    grp_cnn_gesture_core_fu_294_ap_ready;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_0_0_address0;
wire    grp_cnn_gesture_core_fu_294_input_0_0_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_0_1_address0;
wire    grp_cnn_gesture_core_fu_294_input_0_1_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_0_2_address0;
wire    grp_cnn_gesture_core_fu_294_input_0_2_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_0_3_address0;
wire    grp_cnn_gesture_core_fu_294_input_0_3_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_0_4_address0;
wire    grp_cnn_gesture_core_fu_294_input_0_4_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_0_5_address0;
wire    grp_cnn_gesture_core_fu_294_input_0_5_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_1_0_address0;
wire    grp_cnn_gesture_core_fu_294_input_1_0_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_1_1_address0;
wire    grp_cnn_gesture_core_fu_294_input_1_1_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_1_2_address0;
wire    grp_cnn_gesture_core_fu_294_input_1_2_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_1_3_address0;
wire    grp_cnn_gesture_core_fu_294_input_1_3_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_1_4_address0;
wire    grp_cnn_gesture_core_fu_294_input_1_4_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_1_5_address0;
wire    grp_cnn_gesture_core_fu_294_input_1_5_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_2_0_address0;
wire    grp_cnn_gesture_core_fu_294_input_2_0_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_2_1_address0;
wire    grp_cnn_gesture_core_fu_294_input_2_1_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_2_2_address0;
wire    grp_cnn_gesture_core_fu_294_input_2_2_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_2_3_address0;
wire    grp_cnn_gesture_core_fu_294_input_2_3_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_2_4_address0;
wire    grp_cnn_gesture_core_fu_294_input_2_4_ce0;
wire   [5:0] grp_cnn_gesture_core_fu_294_input_2_5_address0;
wire    grp_cnn_gesture_core_fu_294_input_2_5_ce0;
wire   [2:0] grp_cnn_gesture_core_fu_294_output_r_address0;
wire    grp_cnn_gesture_core_fu_294_output_r_ce0;
wire    grp_cnn_gesture_core_fu_294_output_r_we0;
wire   [15:0] grp_cnn_gesture_core_fu_294_output_r_d0;
wire   [31:0] grp_cnn_gesture_core_fu_294_grp_fu_462_p_din0;
wire    grp_cnn_gesture_core_fu_294_grp_fu_462_p_ce;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_done;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_idle;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_ready;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TREADY;
wire   [2:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_r_address0;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_r_ce0;
wire   [31:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TDATA;
wire    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID;
wire   [3:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TKEEP;
wire   [3:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TSTRB;
wire   [0:0] grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TLAST;
reg    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_cnn_gesture_core_fu_294_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [31:0] output_stream_TDATA_reg;
reg   [3:0] output_stream_TKEEP_reg;
reg   [3:0] output_stream_TSTRB_reg;
reg   [0:0] output_stream_TLAST_reg;
wire   [63:0] grp_fu_462_p1;
reg   [31:0] grp_fu_462_p0;
reg    grp_fu_462_ce;
wire    ap_CS_fsm_state8;
wire    regslice_both_output_stream_V_data_V_U_apdone_blk;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_input_stream_V_data_V_U_apdone_blk;
wire   [31:0] input_stream_TDATA_int_regslice;
wire    input_stream_TVALID_int_regslice;
reg    input_stream_TREADY_int_regslice;
wire    regslice_both_input_stream_V_data_V_U_ack_in;
wire    regslice_both_input_stream_V_keep_V_U_apdone_blk;
wire   [3:0] input_stream_TKEEP_int_regslice;
wire    regslice_both_input_stream_V_keep_V_U_vld_out;
wire    regslice_both_input_stream_V_keep_V_U_ack_in;
wire    regslice_both_input_stream_V_strb_V_U_apdone_blk;
wire   [3:0] input_stream_TSTRB_int_regslice;
wire    regslice_both_input_stream_V_strb_V_U_vld_out;
wire    regslice_both_input_stream_V_strb_V_U_ack_in;
wire    regslice_both_input_stream_V_last_V_U_apdone_blk;
wire   [0:0] input_stream_TLAST_int_regslice;
wire    regslice_both_input_stream_V_last_V_U_vld_out;
wire    regslice_both_input_stream_V_last_V_U_ack_in;
reg   [31:0] output_stream_TDATA_int_regslice;
wire    output_stream_TVALID_int_regslice;
wire    output_stream_TREADY_int_regslice;
wire    regslice_both_output_stream_V_data_V_U_vld_out;
wire    regslice_both_output_stream_V_keep_V_U_apdone_blk;
reg   [3:0] output_stream_TKEEP_int_regslice;
wire    regslice_both_output_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_keep_V_U_vld_out;
wire    regslice_both_output_stream_V_strb_V_U_apdone_blk;
reg   [3:0] output_stream_TSTRB_int_regslice;
wire    regslice_both_output_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_strb_V_U_vld_out;
wire    regslice_both_output_stream_V_last_V_U_apdone_blk;
reg   [0:0] output_stream_TLAST_int_regslice;
wire    regslice_both_output_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start_reg = 1'b0;
#0 grp_cnn_gesture_core_fu_294_ap_start_reg = 1'b0;
#0 grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start_reg = 1'b0;
end

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_address0),
    .ce0(input_ce0),
    .we0(input_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_d0),
    .q0(input_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_1_address0),
    .ce0(input_1_ce0),
    .we0(input_1_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_d0),
    .q0(input_1_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_2_address0),
    .ce0(input_2_ce0),
    .we0(input_2_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_d0),
    .q0(input_2_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_3_address0),
    .ce0(input_3_ce0),
    .we0(input_3_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_d0),
    .q0(input_3_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_4_address0),
    .ce0(input_4_ce0),
    .we0(input_4_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_d0),
    .q0(input_4_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_5_address0),
    .ce0(input_5_ce0),
    .we0(input_5_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_d0),
    .q0(input_5_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_6_address0),
    .ce0(input_6_ce0),
    .we0(input_6_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_d0),
    .q0(input_6_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_7_address0),
    .ce0(input_7_ce0),
    .we0(input_7_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_d0),
    .q0(input_7_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_8_address0),
    .ce0(input_8_ce0),
    .we0(input_8_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_d0),
    .q0(input_8_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_9_address0),
    .ce0(input_9_ce0),
    .we0(input_9_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_d0),
    .q0(input_9_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_10_address0),
    .ce0(input_10_ce0),
    .we0(input_10_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_d0),
    .q0(input_10_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_11_address0),
    .ce0(input_11_ce0),
    .we0(input_11_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_d0),
    .q0(input_11_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_12_address0),
    .ce0(input_12_ce0),
    .we0(input_12_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_d0),
    .q0(input_12_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_13_address0),
    .ce0(input_13_ce0),
    .we0(input_13_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_d0),
    .q0(input_13_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_14_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_14_address0),
    .ce0(input_14_ce0),
    .we0(input_14_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_d0),
    .q0(input_14_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_15_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_15_address0),
    .ce0(input_15_ce0),
    .we0(input_15_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_d0),
    .q0(input_15_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_16_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_16_address0),
    .ce0(input_16_ce0),
    .we0(input_16_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_d0),
    .q0(input_16_q0)
);

cnn_gesture_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
input_17_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_17_address0),
    .ce0(input_17_ce0),
    .we0(input_17_we0),
    .d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_d0),
    .q0(input_17_q0)
);

cnn_gesture_top_output_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
output_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_address0),
    .ce0(output_ce0),
    .we0(output_we0),
    .d0(grp_cnn_gesture_core_fu_294_output_r_d0),
    .q0(output_q0)
);

cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2 grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start),
    .ap_done(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_done),
    .ap_idle(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_idle),
    .ap_ready(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_ready),
    .input_stream_TVALID(input_stream_TVALID_int_regslice),
    .input_r_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_address0),
    .input_r_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_ce0),
    .input_r_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_we0),
    .input_r_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_d0),
    .input_1_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_address0),
    .input_1_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_ce0),
    .input_1_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_we0),
    .input_1_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_d0),
    .input_2_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_address0),
    .input_2_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_ce0),
    .input_2_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_we0),
    .input_2_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_d0),
    .input_3_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_address0),
    .input_3_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_ce0),
    .input_3_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_we0),
    .input_3_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_d0),
    .input_4_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_address0),
    .input_4_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_ce0),
    .input_4_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_we0),
    .input_4_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_d0),
    .input_5_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_address0),
    .input_5_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_ce0),
    .input_5_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_we0),
    .input_5_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_d0),
    .input_6_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_address0),
    .input_6_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_ce0),
    .input_6_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_we0),
    .input_6_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_d0),
    .input_7_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_address0),
    .input_7_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_ce0),
    .input_7_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_we0),
    .input_7_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_d0),
    .input_8_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_address0),
    .input_8_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_ce0),
    .input_8_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_we0),
    .input_8_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_d0),
    .input_9_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_address0),
    .input_9_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_ce0),
    .input_9_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_we0),
    .input_9_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_d0),
    .input_10_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_address0),
    .input_10_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_ce0),
    .input_10_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_we0),
    .input_10_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_d0),
    .input_11_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_address0),
    .input_11_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_ce0),
    .input_11_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_we0),
    .input_11_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_d0),
    .input_12_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_address0),
    .input_12_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_ce0),
    .input_12_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_we0),
    .input_12_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_d0),
    .input_13_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_address0),
    .input_13_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_ce0),
    .input_13_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_we0),
    .input_13_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_d0),
    .input_14_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_address0),
    .input_14_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_ce0),
    .input_14_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_we0),
    .input_14_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_d0),
    .input_15_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_address0),
    .input_15_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_ce0),
    .input_15_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_we0),
    .input_15_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_d0),
    .input_16_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_address0),
    .input_16_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_ce0),
    .input_16_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_we0),
    .input_16_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_d0),
    .input_17_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_address0),
    .input_17_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_ce0),
    .input_17_we0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_we0),
    .input_17_d0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_d0),
    .input_stream_TDATA(input_stream_TDATA_int_regslice),
    .input_stream_TREADY(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_TKEEP_int_regslice),
    .input_stream_TSTRB(input_stream_TSTRB_int_regslice),
    .input_stream_TLAST(input_stream_TLAST_int_regslice),
    .grp_fu_462_p_din0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_grp_fu_462_p_din0),
    .grp_fu_462_p_dout0(grp_fu_462_p1),
    .grp_fu_462_p_ce(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_grp_fu_462_p_ce)
);

cnn_gesture_top_cnn_gesture_core grp_cnn_gesture_core_fu_294(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_gesture_core_fu_294_ap_start),
    .ap_done(grp_cnn_gesture_core_fu_294_ap_done),
    .ap_idle(grp_cnn_gesture_core_fu_294_ap_idle),
    .ap_ready(grp_cnn_gesture_core_fu_294_ap_ready),
    .input_0_0_address0(grp_cnn_gesture_core_fu_294_input_0_0_address0),
    .input_0_0_ce0(grp_cnn_gesture_core_fu_294_input_0_0_ce0),
    .input_0_0_q0(input_q0),
    .input_0_1_address0(grp_cnn_gesture_core_fu_294_input_0_1_address0),
    .input_0_1_ce0(grp_cnn_gesture_core_fu_294_input_0_1_ce0),
    .input_0_1_q0(input_1_q0),
    .input_0_2_address0(grp_cnn_gesture_core_fu_294_input_0_2_address0),
    .input_0_2_ce0(grp_cnn_gesture_core_fu_294_input_0_2_ce0),
    .input_0_2_q0(input_2_q0),
    .input_0_3_address0(grp_cnn_gesture_core_fu_294_input_0_3_address0),
    .input_0_3_ce0(grp_cnn_gesture_core_fu_294_input_0_3_ce0),
    .input_0_3_q0(input_3_q0),
    .input_0_4_address0(grp_cnn_gesture_core_fu_294_input_0_4_address0),
    .input_0_4_ce0(grp_cnn_gesture_core_fu_294_input_0_4_ce0),
    .input_0_4_q0(input_4_q0),
    .input_0_5_address0(grp_cnn_gesture_core_fu_294_input_0_5_address0),
    .input_0_5_ce0(grp_cnn_gesture_core_fu_294_input_0_5_ce0),
    .input_0_5_q0(input_5_q0),
    .input_1_0_address0(grp_cnn_gesture_core_fu_294_input_1_0_address0),
    .input_1_0_ce0(grp_cnn_gesture_core_fu_294_input_1_0_ce0),
    .input_1_0_q0(input_6_q0),
    .input_1_1_address0(grp_cnn_gesture_core_fu_294_input_1_1_address0),
    .input_1_1_ce0(grp_cnn_gesture_core_fu_294_input_1_1_ce0),
    .input_1_1_q0(input_7_q0),
    .input_1_2_address0(grp_cnn_gesture_core_fu_294_input_1_2_address0),
    .input_1_2_ce0(grp_cnn_gesture_core_fu_294_input_1_2_ce0),
    .input_1_2_q0(input_8_q0),
    .input_1_3_address0(grp_cnn_gesture_core_fu_294_input_1_3_address0),
    .input_1_3_ce0(grp_cnn_gesture_core_fu_294_input_1_3_ce0),
    .input_1_3_q0(input_9_q0),
    .input_1_4_address0(grp_cnn_gesture_core_fu_294_input_1_4_address0),
    .input_1_4_ce0(grp_cnn_gesture_core_fu_294_input_1_4_ce0),
    .input_1_4_q0(input_10_q0),
    .input_1_5_address0(grp_cnn_gesture_core_fu_294_input_1_5_address0),
    .input_1_5_ce0(grp_cnn_gesture_core_fu_294_input_1_5_ce0),
    .input_1_5_q0(input_11_q0),
    .input_2_0_address0(grp_cnn_gesture_core_fu_294_input_2_0_address0),
    .input_2_0_ce0(grp_cnn_gesture_core_fu_294_input_2_0_ce0),
    .input_2_0_q0(input_12_q0),
    .input_2_1_address0(grp_cnn_gesture_core_fu_294_input_2_1_address0),
    .input_2_1_ce0(grp_cnn_gesture_core_fu_294_input_2_1_ce0),
    .input_2_1_q0(input_13_q0),
    .input_2_2_address0(grp_cnn_gesture_core_fu_294_input_2_2_address0),
    .input_2_2_ce0(grp_cnn_gesture_core_fu_294_input_2_2_ce0),
    .input_2_2_q0(input_14_q0),
    .input_2_3_address0(grp_cnn_gesture_core_fu_294_input_2_3_address0),
    .input_2_3_ce0(grp_cnn_gesture_core_fu_294_input_2_3_ce0),
    .input_2_3_q0(input_15_q0),
    .input_2_4_address0(grp_cnn_gesture_core_fu_294_input_2_4_address0),
    .input_2_4_ce0(grp_cnn_gesture_core_fu_294_input_2_4_ce0),
    .input_2_4_q0(input_16_q0),
    .input_2_5_address0(grp_cnn_gesture_core_fu_294_input_2_5_address0),
    .input_2_5_ce0(grp_cnn_gesture_core_fu_294_input_2_5_ce0),
    .input_2_5_q0(input_17_q0),
    .output_r_address0(grp_cnn_gesture_core_fu_294_output_r_address0),
    .output_r_ce0(grp_cnn_gesture_core_fu_294_output_r_ce0),
    .output_r_we0(grp_cnn_gesture_core_fu_294_output_r_we0),
    .output_r_d0(grp_cnn_gesture_core_fu_294_output_r_d0),
    .grp_fu_462_p_din0(grp_cnn_gesture_core_fu_294_grp_fu_462_p_din0),
    .grp_fu_462_p_dout0(grp_fu_462_p1),
    .grp_fu_462_p_ce(grp_cnn_gesture_core_fu_294_grp_fu_462_p_ce)
);

cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3 grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start),
    .ap_done(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_done),
    .ap_idle(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_idle),
    .ap_ready(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_ready),
    .output_stream_TREADY(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TREADY),
    .output_r_address0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_r_address0),
    .output_r_ce0(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_r_ce0),
    .output_r_q0(output_q0),
    .output_stream_TDATA(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TDATA),
    .output_stream_TVALID(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID),
    .output_stream_TKEEP(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TKEEP),
    .output_stream_TSTRB(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TSTRB),
    .output_stream_TLAST(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TLAST)
);

cnn_gesture_top_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cnn_gesture_top_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U648(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_462_p0),
    .ce(grp_fu_462_ce),
    .dout(grp_fu_462_p1)
);

cnn_gesture_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_input_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TDATA),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_data_V_U_ack_in),
    .data_out(input_stream_TDATA_int_regslice),
    .vld_out(input_stream_TVALID_int_regslice),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_data_V_U_apdone_blk)
);

cnn_gesture_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TKEEP),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_keep_V_U_ack_in),
    .data_out(input_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream_V_keep_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_keep_V_U_apdone_blk)
);

cnn_gesture_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TSTRB),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_strb_V_U_ack_in),
    .data_out(input_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream_V_strb_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_strb_V_U_apdone_blk)
);

cnn_gesture_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TLAST),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_last_V_U_ack_in),
    .data_out(input_stream_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream_V_last_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_last_V_U_apdone_blk)
);

cnn_gesture_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TDATA_int_regslice),
    .vld_in(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID),
    .ack_in(output_stream_TREADY_int_regslice),
    .data_out(output_stream_TDATA),
    .vld_out(regslice_both_output_stream_V_data_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_data_V_U_apdone_blk)
);

cnn_gesture_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TKEEP_int_regslice),
    .vld_in(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_keep_V_U_ack_in_dummy),
    .data_out(output_stream_TKEEP),
    .vld_out(regslice_both_output_stream_V_keep_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_keep_V_U_apdone_blk)
);

cnn_gesture_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TSTRB_int_regslice),
    .vld_in(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_strb_V_U_ack_in_dummy),
    .data_out(output_stream_TSTRB),
    .vld_out(regslice_both_output_stream_V_strb_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_strb_V_U_apdone_blk)
);

cnn_gesture_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TLAST_int_regslice),
    .vld_in(grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_last_V_U_ack_in_dummy),
    .data_out(output_stream_TLAST),
    .vld_out(regslice_both_output_stream_V_last_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_gesture_core_fu_294_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_cnn_gesture_core_fu_294_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_gesture_core_fu_294_ap_ready == 1'b1)) begin
            grp_cnn_gesture_core_fu_294_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_ready == 1'b1)) begin
            grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_ready == 1'b1)) begin
            grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        output_stream_TDATA_reg <= grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TDATA;
        output_stream_TKEEP_reg <= grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TKEEP;
        output_stream_TLAST_reg <= grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TLAST;
        output_stream_TSTRB_reg <= grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TSTRB;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_gesture_core_fu_294_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_462_ce = grp_cnn_gesture_core_fu_294_grp_fu_462_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_462_ce = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_grp_fu_462_p_ce;
    end else begin
        grp_fu_462_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_462_p0 = grp_cnn_gesture_core_fu_294_grp_fu_462_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_462_p0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_grp_fu_462_p_din0;
    end else begin
        grp_fu_462_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_10_address0 = grp_cnn_gesture_core_fu_294_input_1_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_10_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_address0;
    end else begin
        input_10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_10_ce0 = grp_cnn_gesture_core_fu_294_input_1_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_10_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_ce0;
    end else begin
        input_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_10_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_10_we0;
    end else begin
        input_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_11_address0 = grp_cnn_gesture_core_fu_294_input_1_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_11_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_address0;
    end else begin
        input_11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_11_ce0 = grp_cnn_gesture_core_fu_294_input_1_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_11_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_ce0;
    end else begin
        input_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_11_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_11_we0;
    end else begin
        input_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_12_address0 = grp_cnn_gesture_core_fu_294_input_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_12_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_address0;
    end else begin
        input_12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_12_ce0 = grp_cnn_gesture_core_fu_294_input_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_12_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_ce0;
    end else begin
        input_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_12_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_12_we0;
    end else begin
        input_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_13_address0 = grp_cnn_gesture_core_fu_294_input_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_13_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_address0;
    end else begin
        input_13_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_13_ce0 = grp_cnn_gesture_core_fu_294_input_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_13_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_ce0;
    end else begin
        input_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_13_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_13_we0;
    end else begin
        input_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_14_address0 = grp_cnn_gesture_core_fu_294_input_2_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_14_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_address0;
    end else begin
        input_14_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_14_ce0 = grp_cnn_gesture_core_fu_294_input_2_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_14_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_ce0;
    end else begin
        input_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_14_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_14_we0;
    end else begin
        input_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_15_address0 = grp_cnn_gesture_core_fu_294_input_2_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_15_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_address0;
    end else begin
        input_15_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_15_ce0 = grp_cnn_gesture_core_fu_294_input_2_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_15_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_ce0;
    end else begin
        input_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_15_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_15_we0;
    end else begin
        input_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_16_address0 = grp_cnn_gesture_core_fu_294_input_2_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_16_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_address0;
    end else begin
        input_16_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_16_ce0 = grp_cnn_gesture_core_fu_294_input_2_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_16_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_ce0;
    end else begin
        input_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_16_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_16_we0;
    end else begin
        input_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_17_address0 = grp_cnn_gesture_core_fu_294_input_2_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_17_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_address0;
    end else begin
        input_17_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_17_ce0 = grp_cnn_gesture_core_fu_294_input_2_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_17_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_ce0;
    end else begin
        input_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_17_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_17_we0;
    end else begin
        input_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_1_address0 = grp_cnn_gesture_core_fu_294_input_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_1_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_address0;
    end else begin
        input_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_1_ce0 = grp_cnn_gesture_core_fu_294_input_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_1_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_ce0;
    end else begin
        input_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_1_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_1_we0;
    end else begin
        input_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_2_address0 = grp_cnn_gesture_core_fu_294_input_0_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_2_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_address0;
    end else begin
        input_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_2_ce0 = grp_cnn_gesture_core_fu_294_input_0_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_2_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_ce0;
    end else begin
        input_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_2_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_2_we0;
    end else begin
        input_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_3_address0 = grp_cnn_gesture_core_fu_294_input_0_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_3_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_address0;
    end else begin
        input_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_3_ce0 = grp_cnn_gesture_core_fu_294_input_0_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_3_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_ce0;
    end else begin
        input_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_3_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_3_we0;
    end else begin
        input_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_4_address0 = grp_cnn_gesture_core_fu_294_input_0_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_4_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_address0;
    end else begin
        input_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_4_ce0 = grp_cnn_gesture_core_fu_294_input_0_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_4_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_ce0;
    end else begin
        input_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_4_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_4_we0;
    end else begin
        input_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_5_address0 = grp_cnn_gesture_core_fu_294_input_0_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_5_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_address0;
    end else begin
        input_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_5_ce0 = grp_cnn_gesture_core_fu_294_input_0_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_5_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_ce0;
    end else begin
        input_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_5_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_5_we0;
    end else begin
        input_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_6_address0 = grp_cnn_gesture_core_fu_294_input_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_6_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_address0;
    end else begin
        input_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_6_ce0 = grp_cnn_gesture_core_fu_294_input_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_6_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_ce0;
    end else begin
        input_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_6_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_6_we0;
    end else begin
        input_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_7_address0 = grp_cnn_gesture_core_fu_294_input_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_7_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_address0;
    end else begin
        input_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_7_ce0 = grp_cnn_gesture_core_fu_294_input_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_7_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_ce0;
    end else begin
        input_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_7_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_7_we0;
    end else begin
        input_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_8_address0 = grp_cnn_gesture_core_fu_294_input_1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_8_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_address0;
    end else begin
        input_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_8_ce0 = grp_cnn_gesture_core_fu_294_input_1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_8_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_ce0;
    end else begin
        input_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_8_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_8_we0;
    end else begin
        input_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_9_address0 = grp_cnn_gesture_core_fu_294_input_1_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_9_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_address0;
    end else begin
        input_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_9_ce0 = grp_cnn_gesture_core_fu_294_input_1_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_9_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_ce0;
    end else begin
        input_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_9_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_9_we0;
    end else begin
        input_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_address0 = grp_cnn_gesture_core_fu_294_input_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_address0;
    end else begin
        input_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_ce0 = grp_cnn_gesture_core_fu_294_input_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_ce0;
    end else begin
        input_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_TREADY_int_regslice = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_stream_TREADY;
    end else begin
        input_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_we0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_input_r_we0;
    end else begin
        input_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        output_address0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        output_address0 = grp_cnn_gesture_core_fu_294_output_r_address0;
    end else begin
        output_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        output_ce0 = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        output_ce0 = grp_cnn_gesture_core_fu_294_output_r_ce0;
    end else begin
        output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        output_stream_TDATA_int_regslice = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TDATA;
    end else begin
        output_stream_TDATA_int_regslice = output_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        output_stream_TKEEP_int_regslice = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TKEEP;
    end else begin
        output_stream_TKEEP_int_regslice = output_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        output_stream_TLAST_int_regslice = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TLAST;
    end else begin
        output_stream_TLAST_int_regslice = output_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        output_stream_TSTRB_int_regslice = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TSTRB;
    end else begin
        output_stream_TSTRB_int_regslice = output_stream_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        output_we0 = grp_cnn_gesture_core_fu_294_output_r_we0;
    end else begin
        output_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_cnn_gesture_core_fu_294_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_cnn_gesture_core_fu_294_ap_start = grp_cnn_gesture_core_fu_294_ap_start_reg;

assign grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2_fu_264_ap_start_reg;

assign grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_ap_start_reg;

assign grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TREADY = (output_stream_TREADY_int_regslice & ap_CS_fsm_state7);

assign input_stream_TREADY = regslice_both_input_stream_V_data_V_U_ack_in;

assign output_stream_TVALID = regslice_both_output_stream_V_data_V_U_vld_out;

assign output_stream_TVALID_int_regslice = grp_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3_fu_449_output_stream_TVALID;

endmodule //cnn_gesture_top
