// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_160_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln158_2,
        empty,
        flat_address0,
        flat_ce0,
        flat_q0,
        sum_9_out,
        sum_9_out_ap_vld,
        grp_fu_724_p_din0,
        grp_fu_724_p_dout0,
        grp_fu_724_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [25:0] sext_ln158_2;
input  [6:0] empty;
output  [10:0] flat_address0;
output   flat_ce0;
input  [15:0] flat_q0;
output  [25:0] sum_9_out;
output   sum_9_out_ap_vld;
output  [31:0] grp_fu_724_p_din0;
input  [63:0] grp_fu_724_p_dout0;
output   grp_fu_724_p_ce;

reg ap_idle;
reg sum_9_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln160_fu_170_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [17:0] dense_param_0_address0;
wire   [31:0] dense_param_0_q0;
wire    ap_block_pp0_stage0_11001;
reg   [10:0] i_reg_490;
reg   [10:0] i_reg_490_pp0_iter1_reg;
reg   [0:0] icmp_ln160_reg_495;
reg   [0:0] icmp_ln160_reg_495_pp0_iter1_reg;
reg   [0:0] icmp_ln160_reg_495_pp0_iter2_reg;
reg   [0:0] icmp_ln160_reg_495_pp0_iter3_reg;
reg   [0:0] icmp_ln160_reg_495_pp0_iter4_reg;
wire   [15:0] storemerge4_i8_fu_424_p11;
reg  signed [15:0] storemerge4_i8_reg_509;
reg    ap_condition_exit_pp0_iter5_stage0;
wire   [63:0] zext_ln162_1_fu_190_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln160_fu_200_p1;
reg   [31:0] sum_9_fu_96;
wire  signed [31:0] grp_fu_467_p3;
wire  signed [31:0] sext_ln158_2_cast_fu_153_p1;
reg  signed [31:0] ap_sig_allocacmp_sum;
wire    ap_loop_init;
reg   [10:0] i_2_fu_100;
wire   [10:0] add_ln160_fu_176_p2;
reg   [10:0] ap_sig_allocacmp_i;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
wire    ap_block_pp0_stage0_01001;
reg    dense_param_0_ce0_local;
reg    flat_ce0_local;
wire   [17:0] wi_6_fu_182_p3;
wire   [63:0] bitcast_ln726_10_fu_204_p1;
wire   [10:0] tmp_42_fu_220_p3;
wire   [51:0] trunc_ln162_1_fu_232_p1;
wire   [52:0] zext_ln162_3_cast_fu_236_p3;
wire   [53:0] zext_ln162_3_fu_244_p1;
wire   [0:0] tmp_238_fu_212_p3;
wire   [53:0] sub_ln162_fu_248_p2;
wire   [62:0] trunc_ln162_fu_208_p1;
wire   [11:0] zext_ln162_fu_228_p1;
wire   [11:0] sub_ln162_1_fu_268_p2;
wire   [10:0] trunc_ln162_2_fu_274_p1;
wire   [0:0] icmp_ln162_1_fu_278_p2;
wire   [10:0] add_ln162_fu_284_p2;
wire   [10:0] sub_ln162_2_fu_290_p2;
wire   [53:0] select_ln162_fu_254_p3;
wire   [10:0] select_ln162_1_fu_296_p3;
wire   [53:0] zext_ln162_2_fu_328_p1;
wire   [53:0] ashr_ln162_fu_332_p2;
wire   [0:0] icmp_ln162_3_fu_314_p2;
wire   [15:0] trunc_ln162_4_fu_338_p1;
wire   [15:0] select_ln162_4_fu_320_p3;
wire   [6:0] tmp_239_fu_350_p4;
wire   [15:0] trunc_ln162_3_fu_310_p1;
wire   [15:0] select_ln162_1cast_fu_366_p1;
wire   [0:0] icmp_ln162_4_fu_360_p2;
wire   [15:0] shl_ln162_fu_370_p2;
wire   [0:0] icmp_ln162_fu_262_p2;
wire   [0:0] icmp_ln162_2_fu_304_p2;
wire   [0:0] xor_ln162_fu_384_p2;
wire   [0:0] or_ln162_fu_396_p2;
wire   [0:0] xor_ln162_1_fu_402_p2;
wire   [0:0] and_ln162_fu_390_p2;
wire   [0:0] and_ln162_1_fu_408_p2;
wire   [15:0] storemerge4_i8_fu_424_p6;
wire   [15:0] storemerge4_i8_fu_424_p8;
wire   [15:0] storemerge4_i8_fu_424_p9;
wire   [2:0] storemerge4_i8_fu_424_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [2:0] storemerge4_i8_fu_424_p1;
wire   [2:0] storemerge4_i8_fu_424_p3;
wire   [2:0] storemerge4_i8_fu_424_p5;
wire   [2:0] storemerge4_i8_fu_424_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 sum_9_fu_96 = 32'd0;
#0 i_2_fu_100 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_160_2_dense_param_0_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 204800 ),
    .AddressWidth( 18 ))
dense_param_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_param_0_address0),
    .ce0(dense_param_0_ce0_local),
    .q0(dense_param_0_q0)
);

(* dissolve_hierarchy = "yes" *) cnn_gesture_top_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U390(
    .din0(16'd0),
    .din1(trunc_ln162_3_fu_310_p1),
    .din2(storemerge4_i8_fu_424_p6),
    .din3(storemerge4_i8_fu_424_p8),
    .def(storemerge4_i8_fu_424_p9),
    .sel(storemerge4_i8_fu_424_p10),
    .dout(storemerge4_i8_fu_424_p11)
);

cnn_gesture_top_mac_muladd_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_4_1_U391(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(flat_q0),
    .din1(storemerge4_i8_reg_509),
    .din2(ap_sig_allocacmp_sum),
    .ce(1'b1),
    .dout(grp_fu_467_p3)
);

cnn_gesture_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter5_stage0)) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln160_fu_170_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_2_fu_100 <= add_ln160_fu_176_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_2_fu_100 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            sum_9_fu_96 <= sext_ln158_2_cast_fu_153_p1;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            sum_9_fu_96 <= grp_fu_467_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_reg_490 <= ap_sig_allocacmp_i;
        i_reg_490_pp0_iter1_reg <= i_reg_490;
        icmp_ln160_reg_495 <= icmp_ln160_fu_170_p2;
        icmp_ln160_reg_495_pp0_iter1_reg <= icmp_ln160_reg_495;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln160_reg_495_pp0_iter2_reg <= icmp_ln160_reg_495_pp0_iter1_reg;
        icmp_ln160_reg_495_pp0_iter3_reg <= icmp_ln160_reg_495_pp0_iter2_reg;
        icmp_ln160_reg_495_pp0_iter4_reg <= icmp_ln160_reg_495_pp0_iter3_reg;
        storemerge4_i8_reg_509 <= storemerge4_i8_fu_424_p11;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_170_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_reg_495_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 11'd0;
    end else begin
        ap_sig_allocacmp_i = i_2_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_sum = grp_fu_467_p3;
    end else begin
        ap_sig_allocacmp_sum = sum_9_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense_param_0_ce0_local = 1'b1;
    end else begin
        dense_param_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        flat_ce0_local = 1'b1;
    end else begin
        flat_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_reg_495_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        sum_9_out_ap_vld = 1'b1;
    end else begin
        sum_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_fu_176_p2 = (ap_sig_allocacmp_i + 11'd1);

assign add_ln162_fu_284_p2 = ($signed(trunc_ln162_2_fu_274_p1) + $signed(11'd2038));

assign and_ln162_1_fu_408_p2 = (xor_ln162_1_fu_402_p2 & icmp_ln162_1_fu_278_p2);

assign and_ln162_fu_390_p2 = (xor_ln162_fu_384_p2 & icmp_ln162_2_fu_304_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ashr_ln162_fu_332_p2 = $signed(select_ln162_fu_254_p3) >>> zext_ln162_2_fu_328_p1;

assign bitcast_ln726_10_fu_204_p1 = grp_fu_724_p_dout0;

assign dense_param_0_address0 = zext_ln162_1_fu_190_p1;

assign flat_address0 = zext_ln160_fu_200_p1;

assign flat_ce0 = flat_ce0_local;

assign grp_fu_724_p_ce = 1'b1;

assign grp_fu_724_p_din0 = dense_param_0_q0;

assign icmp_ln160_fu_170_p2 = ((ap_sig_allocacmp_i == 11'd1600) ? 1'b1 : 1'b0);

assign icmp_ln162_1_fu_278_p2 = (($signed(sub_ln162_1_fu_268_p2) > $signed(12'd10)) ? 1'b1 : 1'b0);

assign icmp_ln162_2_fu_304_p2 = ((sub_ln162_1_fu_268_p2 == 12'd10) ? 1'b1 : 1'b0);

assign icmp_ln162_3_fu_314_p2 = ((select_ln162_1_fu_296_p3 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln162_4_fu_360_p2 = ((tmp_239_fu_350_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_262_p2 = ((trunc_ln162_fu_208_p1 == 63'd0) ? 1'b1 : 1'b0);

assign or_ln162_fu_396_p2 = (icmp_ln162_fu_262_p2 | icmp_ln162_2_fu_304_p2);

assign select_ln162_1_fu_296_p3 = ((icmp_ln162_1_fu_278_p2[0:0] == 1'b1) ? add_ln162_fu_284_p2 : sub_ln162_2_fu_290_p2);

assign select_ln162_1cast_fu_366_p1 = select_ln162_1_fu_296_p3;

assign select_ln162_4_fu_320_p3 = ((tmp_238_fu_212_p3[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln162_fu_254_p3 = ((tmp_238_fu_212_p3[0:0] == 1'b1) ? sub_ln162_fu_248_p2 : zext_ln162_3_fu_244_p1);

assign sext_ln158_2_cast_fu_153_p1 = $signed(sext_ln158_2);

assign shl_ln162_fu_370_p2 = trunc_ln162_3_fu_310_p1 << select_ln162_1cast_fu_366_p1;

assign storemerge4_i8_fu_424_p10 = {{{icmp_ln162_fu_262_p2}, {and_ln162_fu_390_p2}}, {and_ln162_1_fu_408_p2}};

assign storemerge4_i8_fu_424_p6 = ((icmp_ln162_3_fu_314_p2[0:0] == 1'b1) ? trunc_ln162_4_fu_338_p1 : select_ln162_4_fu_320_p3);

assign storemerge4_i8_fu_424_p8 = ((icmp_ln162_4_fu_360_p2[0:0] == 1'b1) ? shl_ln162_fu_370_p2 : 16'd0);

assign storemerge4_i8_fu_424_p9 = 'bx;

assign sub_ln162_1_fu_268_p2 = (12'd1075 - zext_ln162_fu_228_p1);

assign sub_ln162_2_fu_290_p2 = (11'd10 - trunc_ln162_2_fu_274_p1);

assign sub_ln162_fu_248_p2 = (54'd0 - zext_ln162_3_fu_244_p1);

assign sum_9_out = ap_sig_allocacmp_sum[25:0];

assign tmp_238_fu_212_p3 = bitcast_ln726_10_fu_204_p1[32'd63];

assign tmp_239_fu_350_p4 = {{select_ln162_1_fu_296_p3[10:4]}};

assign tmp_42_fu_220_p3 = {{bitcast_ln726_10_fu_204_p1[62:52]}};

assign trunc_ln162_1_fu_232_p1 = bitcast_ln726_10_fu_204_p1[51:0];

assign trunc_ln162_2_fu_274_p1 = sub_ln162_1_fu_268_p2[10:0];

assign trunc_ln162_3_fu_310_p1 = select_ln162_fu_254_p3[15:0];

assign trunc_ln162_4_fu_338_p1 = ashr_ln162_fu_332_p2[15:0];

assign trunc_ln162_fu_208_p1 = bitcast_ln726_10_fu_204_p1[62:0];

assign wi_6_fu_182_p3 = {{ap_sig_allocacmp_i}, {empty}};

assign xor_ln162_1_fu_402_p2 = (or_ln162_fu_396_p2 ^ 1'd1);

assign xor_ln162_fu_384_p2 = (icmp_ln162_fu_262_p2 ^ 1'd1);

assign zext_ln160_fu_200_p1 = i_reg_490_pp0_iter1_reg;

assign zext_ln162_1_fu_190_p1 = wi_6_fu_182_p3;

assign zext_ln162_2_fu_328_p1 = select_ln162_1_fu_296_p3;

assign zext_ln162_3_cast_fu_236_p3 = {{1'd1}, {trunc_ln162_1_fu_232_p1}};

assign zext_ln162_3_fu_244_p1 = zext_ln162_3_cast_fu_236_p3;

assign zext_ln162_fu_228_p1 = tmp_42_fu_220_p3;

endmodule //cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_160_2
