// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_142_1_VITIS_LOOP_143_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool2_out_address0,
        pool2_out_ce0,
        pool2_out_q0,
        flat_address0,
        flat_ce0,
        flat_we0,
        flat_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] pool2_out_address0;
output   pool2_out_ce0;
input  [15:0] pool2_out_q0;
output  [10:0] flat_address0;
output   flat_ce0;
output   flat_we0;
output  [15:0] flat_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln142_fu_125_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln143_fu_149_p2;
reg   [0:0] icmp_ln143_reg_314;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln144_1_fu_189_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln143_fu_238_p1;
reg   [6:0] c_fu_46;
wire   [6:0] add_ln143_fu_194_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_c_load;
reg   [10:0] idx_1_fu_50;
wire   [10:0] add_ln144_fu_243_p2;
reg   [10:0] add_ln142_11_fu_54;
wire   [10:0] add_ln142_1_fu_249_p2;
reg   [10:0] idx_fu_58;
wire   [10:0] select_ln142_3_fu_231_p3;
reg   [4:0] t_fu_62;
wire   [4:0] select_ln142_2_fu_163_p3;
reg   [4:0] ap_sig_allocacmp_t_load;
reg   [10:0] indvar_flatten44_fu_66;
wire   [10:0] add_ln142_2_fu_131_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten44_load;
reg    pool2_out_ce0_local;
reg    flat_we0_local;
reg    flat_ce0_local;
wire   [4:0] add_ln142_fu_143_p2;
wire   [6:0] select_ln142_1_fu_155_p3;
wire   [10:0] tmp_s_fu_171_p3;
wire   [10:0] zext_ln144_fu_179_p1;
wire   [10:0] add_ln144_1_fu_183_p2;
wire   [10:0] select_ln142_fu_224_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 c_fu_46 = 7'd0;
#0 idx_1_fu_50 = 11'd0;
#0 add_ln142_11_fu_54 = 11'd0;
#0 idx_fu_58 = 11'd0;
#0 t_fu_62 = 5'd0;
#0 indvar_flatten44_fu_66 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_gesture_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln142_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_46 <= add_ln143_fu_194_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_46 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_1_fu_50 <= 11'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            idx_1_fu_50 <= add_ln144_fu_243_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_fu_58 <= 11'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            idx_fu_58 <= select_ln142_3_fu_231_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln142_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten44_fu_66 <= add_ln142_2_fu_131_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten44_fu_66 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln142_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_62 <= select_ln142_2_fu_163_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_62 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln142_11_fu_54 <= add_ln142_1_fu_249_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln143_reg_314 <= icmp_ln143_fu_149_p2;
    end
end

always @ (*) begin
    if (((icmp_ln142_fu_125_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 7'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten44_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten44_load = indvar_flatten44_fu_66;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 5'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flat_ce0_local = 1'b1;
    end else begin
        flat_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flat_we0_local = 1'b1;
    end else begin
        flat_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool2_out_ce0_local = 1'b1;
    end else begin
        pool2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln142_1_fu_249_p2 = (select_ln142_3_fu_231_p3 + 11'd64);

assign add_ln142_2_fu_131_p2 = (ap_sig_allocacmp_indvar_flatten44_load + 11'd1);

assign add_ln142_fu_143_p2 = (ap_sig_allocacmp_t_load + 5'd1);

assign add_ln143_fu_194_p2 = (select_ln142_1_fu_155_p3 + 7'd1);

assign add_ln144_1_fu_183_p2 = (tmp_s_fu_171_p3 + zext_ln144_fu_179_p1);

assign add_ln144_fu_243_p2 = (select_ln142_fu_224_p3 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign flat_address0 = zext_ln143_fu_238_p1;

assign flat_ce0 = flat_ce0_local;

assign flat_d0 = pool2_out_q0;

assign flat_we0 = flat_we0_local;

assign icmp_ln142_fu_125_p2 = ((ap_sig_allocacmp_indvar_flatten44_load == 11'd1600) ? 1'b1 : 1'b0);

assign icmp_ln143_fu_149_p2 = ((ap_sig_allocacmp_c_load == 7'd64) ? 1'b1 : 1'b0);

assign pool2_out_address0 = zext_ln144_1_fu_189_p1;

assign pool2_out_ce0 = pool2_out_ce0_local;

assign select_ln142_1_fu_155_p3 = ((icmp_ln143_fu_149_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_c_load);

assign select_ln142_2_fu_163_p3 = ((icmp_ln143_fu_149_p2[0:0] == 1'b1) ? add_ln142_fu_143_p2 : ap_sig_allocacmp_t_load);

assign select_ln142_3_fu_231_p3 = ((icmp_ln143_reg_314[0:0] == 1'b1) ? add_ln142_11_fu_54 : idx_fu_58);

assign select_ln142_fu_224_p3 = ((icmp_ln143_reg_314[0:0] == 1'b1) ? add_ln142_11_fu_54 : idx_1_fu_50);

assign tmp_s_fu_171_p3 = {{select_ln142_2_fu_163_p3}, {6'd0}};

assign zext_ln143_fu_238_p1 = select_ln142_fu_224_p3;

assign zext_ln144_1_fu_189_p1 = add_ln144_1_fu_183_p2;

assign zext_ln144_fu_179_p1 = select_ln142_1_fu_155_p3;

endmodule //cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_142_1_VITIS_LOOP_143_2
