// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_78_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool1_out_address0,
        pool1_out_ce0,
        pool1_out_we0,
        pool1_out_d0,
        pool1_out_1_address0,
        pool1_out_1_ce0,
        pool1_out_1_we0,
        pool1_out_1_d0,
        pool1_out_2_address0,
        pool1_out_2_ce0,
        pool1_out_2_we0,
        pool1_out_2_d0,
        pool1_out_3_address0,
        pool1_out_3_ce0,
        pool1_out_3_we0,
        pool1_out_3_d0,
        pool1_out_4_address0,
        pool1_out_4_ce0,
        pool1_out_4_we0,
        pool1_out_4_d0,
        pool1_out_5_address0,
        pool1_out_5_ce0,
        pool1_out_5_we0,
        pool1_out_5_d0,
        pool1_out_6_address0,
        pool1_out_6_ce0,
        pool1_out_6_we0,
        pool1_out_6_d0,
        pool1_out_7_address0,
        pool1_out_7_ce0,
        pool1_out_7_we0,
        pool1_out_7_d0,
        pool1_out_8_address0,
        pool1_out_8_ce0,
        pool1_out_8_we0,
        pool1_out_8_d0,
        pool1_out_9_address0,
        pool1_out_9_ce0,
        pool1_out_9_we0,
        pool1_out_9_d0,
        pool1_out_10_address0,
        pool1_out_10_ce0,
        pool1_out_10_we0,
        pool1_out_10_d0,
        pool1_out_11_address0,
        pool1_out_11_ce0,
        pool1_out_11_we0,
        pool1_out_11_d0,
        pool1_out_12_address0,
        pool1_out_12_ce0,
        pool1_out_12_we0,
        pool1_out_12_d0,
        pool1_out_13_address0,
        pool1_out_13_ce0,
        pool1_out_13_we0,
        pool1_out_13_d0,
        pool1_out_14_address0,
        pool1_out_14_ce0,
        pool1_out_14_we0,
        pool1_out_14_d0,
        pool1_out_15_address0,
        pool1_out_15_ce0,
        pool1_out_15_we0,
        pool1_out_15_d0,
        pool1_out_16_address0,
        pool1_out_16_ce0,
        pool1_out_16_we0,
        pool1_out_16_d0,
        pool1_out_17_address0,
        pool1_out_17_ce0,
        pool1_out_17_we0,
        pool1_out_17_d0,
        pool1_out_18_address0,
        pool1_out_18_ce0,
        pool1_out_18_we0,
        pool1_out_18_d0,
        pool1_out_19_address0,
        pool1_out_19_ce0,
        pool1_out_19_we0,
        pool1_out_19_d0,
        pool1_out_20_address0,
        pool1_out_20_ce0,
        pool1_out_20_we0,
        pool1_out_20_d0,
        pool1_out_21_address0,
        pool1_out_21_ce0,
        pool1_out_21_we0,
        pool1_out_21_d0,
        pool1_out_22_address0,
        pool1_out_22_ce0,
        pool1_out_22_we0,
        pool1_out_22_d0,
        pool1_out_23_address0,
        pool1_out_23_ce0,
        pool1_out_23_we0,
        pool1_out_23_d0,
        pool1_out_24_address0,
        pool1_out_24_ce0,
        pool1_out_24_we0,
        pool1_out_24_d0,
        pool1_out_25_address0,
        pool1_out_25_ce0,
        pool1_out_25_we0,
        pool1_out_25_d0,
        pool1_out_26_address0,
        pool1_out_26_ce0,
        pool1_out_26_we0,
        pool1_out_26_d0,
        pool1_out_27_address0,
        pool1_out_27_ce0,
        pool1_out_27_we0,
        pool1_out_27_d0,
        pool1_out_28_address0,
        pool1_out_28_ce0,
        pool1_out_28_we0,
        pool1_out_28_d0,
        pool1_out_29_address0,
        pool1_out_29_ce0,
        pool1_out_29_we0,
        pool1_out_29_d0,
        pool1_out_30_address0,
        pool1_out_30_ce0,
        pool1_out_30_we0,
        pool1_out_30_d0,
        pool1_out_31_address0,
        pool1_out_31_ce0,
        pool1_out_31_we0,
        pool1_out_31_d0,
        conv1_out_address0,
        conv1_out_ce0,
        conv1_out_q0,
        conv1_out_address1,
        conv1_out_ce1,
        conv1_out_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] pool1_out_address0;
output   pool1_out_ce0;
output   pool1_out_we0;
output  [15:0] pool1_out_d0;
output  [5:0] pool1_out_1_address0;
output   pool1_out_1_ce0;
output   pool1_out_1_we0;
output  [15:0] pool1_out_1_d0;
output  [5:0] pool1_out_2_address0;
output   pool1_out_2_ce0;
output   pool1_out_2_we0;
output  [15:0] pool1_out_2_d0;
output  [5:0] pool1_out_3_address0;
output   pool1_out_3_ce0;
output   pool1_out_3_we0;
output  [15:0] pool1_out_3_d0;
output  [5:0] pool1_out_4_address0;
output   pool1_out_4_ce0;
output   pool1_out_4_we0;
output  [15:0] pool1_out_4_d0;
output  [5:0] pool1_out_5_address0;
output   pool1_out_5_ce0;
output   pool1_out_5_we0;
output  [15:0] pool1_out_5_d0;
output  [5:0] pool1_out_6_address0;
output   pool1_out_6_ce0;
output   pool1_out_6_we0;
output  [15:0] pool1_out_6_d0;
output  [5:0] pool1_out_7_address0;
output   pool1_out_7_ce0;
output   pool1_out_7_we0;
output  [15:0] pool1_out_7_d0;
output  [5:0] pool1_out_8_address0;
output   pool1_out_8_ce0;
output   pool1_out_8_we0;
output  [15:0] pool1_out_8_d0;
output  [5:0] pool1_out_9_address0;
output   pool1_out_9_ce0;
output   pool1_out_9_we0;
output  [15:0] pool1_out_9_d0;
output  [5:0] pool1_out_10_address0;
output   pool1_out_10_ce0;
output   pool1_out_10_we0;
output  [15:0] pool1_out_10_d0;
output  [5:0] pool1_out_11_address0;
output   pool1_out_11_ce0;
output   pool1_out_11_we0;
output  [15:0] pool1_out_11_d0;
output  [5:0] pool1_out_12_address0;
output   pool1_out_12_ce0;
output   pool1_out_12_we0;
output  [15:0] pool1_out_12_d0;
output  [5:0] pool1_out_13_address0;
output   pool1_out_13_ce0;
output   pool1_out_13_we0;
output  [15:0] pool1_out_13_d0;
output  [5:0] pool1_out_14_address0;
output   pool1_out_14_ce0;
output   pool1_out_14_we0;
output  [15:0] pool1_out_14_d0;
output  [5:0] pool1_out_15_address0;
output   pool1_out_15_ce0;
output   pool1_out_15_we0;
output  [15:0] pool1_out_15_d0;
output  [5:0] pool1_out_16_address0;
output   pool1_out_16_ce0;
output   pool1_out_16_we0;
output  [15:0] pool1_out_16_d0;
output  [5:0] pool1_out_17_address0;
output   pool1_out_17_ce0;
output   pool1_out_17_we0;
output  [15:0] pool1_out_17_d0;
output  [5:0] pool1_out_18_address0;
output   pool1_out_18_ce0;
output   pool1_out_18_we0;
output  [15:0] pool1_out_18_d0;
output  [5:0] pool1_out_19_address0;
output   pool1_out_19_ce0;
output   pool1_out_19_we0;
output  [15:0] pool1_out_19_d0;
output  [5:0] pool1_out_20_address0;
output   pool1_out_20_ce0;
output   pool1_out_20_we0;
output  [15:0] pool1_out_20_d0;
output  [5:0] pool1_out_21_address0;
output   pool1_out_21_ce0;
output   pool1_out_21_we0;
output  [15:0] pool1_out_21_d0;
output  [5:0] pool1_out_22_address0;
output   pool1_out_22_ce0;
output   pool1_out_22_we0;
output  [15:0] pool1_out_22_d0;
output  [5:0] pool1_out_23_address0;
output   pool1_out_23_ce0;
output   pool1_out_23_we0;
output  [15:0] pool1_out_23_d0;
output  [5:0] pool1_out_24_address0;
output   pool1_out_24_ce0;
output   pool1_out_24_we0;
output  [15:0] pool1_out_24_d0;
output  [5:0] pool1_out_25_address0;
output   pool1_out_25_ce0;
output   pool1_out_25_we0;
output  [15:0] pool1_out_25_d0;
output  [5:0] pool1_out_26_address0;
output   pool1_out_26_ce0;
output   pool1_out_26_we0;
output  [15:0] pool1_out_26_d0;
output  [5:0] pool1_out_27_address0;
output   pool1_out_27_ce0;
output   pool1_out_27_we0;
output  [15:0] pool1_out_27_d0;
output  [5:0] pool1_out_28_address0;
output   pool1_out_28_ce0;
output   pool1_out_28_we0;
output  [15:0] pool1_out_28_d0;
output  [5:0] pool1_out_29_address0;
output   pool1_out_29_ce0;
output   pool1_out_29_we0;
output  [15:0] pool1_out_29_d0;
output  [5:0] pool1_out_30_address0;
output   pool1_out_30_ce0;
output   pool1_out_30_we0;
output  [15:0] pool1_out_30_d0;
output  [5:0] pool1_out_31_address0;
output   pool1_out_31_ce0;
output   pool1_out_31_we0;
output  [15:0] pool1_out_31_d0;
output  [11:0] conv1_out_address0;
output   conv1_out_ce0;
input  [15:0] conv1_out_q0;
output  [11:0] conv1_out_address1;
output   conv1_out_ce1;
input  [15:0] conv1_out_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln77_fu_633_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] select_ln77_1_fu_671_p3;
reg   [5:0] select_ln77_1_reg_911;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] trunc_ln78_fu_715_p1;
reg   [4:0] trunc_ln78_reg_926;
wire   [63:0] zext_ln79_fu_699_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln80_fu_710_p1;
wire   [63:0] zext_ln77_fu_806_p1;
reg   [5:0] f_fu_162;
wire   [5:0] add_ln78_fu_785_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_f_load;
reg   [5:0] t_fu_166;
reg   [5:0] ap_sig_allocacmp_t_load;
reg   [10:0] indvar_flatten7_fu_170;
wire   [10:0] add_ln77_1_fu_639_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten7_load;
reg    conv1_out_ce1_local;
reg    conv1_out_ce0_local;
reg    pool1_out_30_we0_local;
wire   [15:0] select_ln81_fu_847_p3;
reg    pool1_out_30_ce0_local;
reg    pool1_out_29_we0_local;
reg    pool1_out_29_ce0_local;
reg    pool1_out_28_we0_local;
reg    pool1_out_28_ce0_local;
reg    pool1_out_27_we0_local;
reg    pool1_out_27_ce0_local;
reg    pool1_out_26_we0_local;
reg    pool1_out_26_ce0_local;
reg    pool1_out_25_we0_local;
reg    pool1_out_25_ce0_local;
reg    pool1_out_24_we0_local;
reg    pool1_out_24_ce0_local;
reg    pool1_out_23_we0_local;
reg    pool1_out_23_ce0_local;
reg    pool1_out_22_we0_local;
reg    pool1_out_22_ce0_local;
reg    pool1_out_21_we0_local;
reg    pool1_out_21_ce0_local;
reg    pool1_out_20_we0_local;
reg    pool1_out_20_ce0_local;
reg    pool1_out_19_we0_local;
reg    pool1_out_19_ce0_local;
reg    pool1_out_18_we0_local;
reg    pool1_out_18_ce0_local;
reg    pool1_out_17_we0_local;
reg    pool1_out_17_ce0_local;
reg    pool1_out_16_we0_local;
reg    pool1_out_16_ce0_local;
reg    pool1_out_15_we0_local;
reg    pool1_out_15_ce0_local;
reg    pool1_out_14_we0_local;
reg    pool1_out_14_ce0_local;
reg    pool1_out_13_we0_local;
reg    pool1_out_13_ce0_local;
reg    pool1_out_12_we0_local;
reg    pool1_out_12_ce0_local;
reg    pool1_out_11_we0_local;
reg    pool1_out_11_ce0_local;
reg    pool1_out_10_we0_local;
reg    pool1_out_10_ce0_local;
reg    pool1_out_9_we0_local;
reg    pool1_out_9_ce0_local;
reg    pool1_out_8_we0_local;
reg    pool1_out_8_ce0_local;
reg    pool1_out_7_we0_local;
reg    pool1_out_7_ce0_local;
reg    pool1_out_6_we0_local;
reg    pool1_out_6_ce0_local;
reg    pool1_out_5_we0_local;
reg    pool1_out_5_ce0_local;
reg    pool1_out_4_we0_local;
reg    pool1_out_4_ce0_local;
reg    pool1_out_3_we0_local;
reg    pool1_out_3_ce0_local;
reg    pool1_out_2_we0_local;
reg    pool1_out_2_ce0_local;
reg    pool1_out_1_we0_local;
reg    pool1_out_1_ce0_local;
reg    pool1_out_we0_local;
reg    pool1_out_ce0_local;
reg    pool1_out_31_we0_local;
reg    pool1_out_31_ce0_local;
wire   [0:0] icmp_ln78_fu_657_p2;
wire   [5:0] add_ln77_fu_651_p2;
wire   [5:0] select_ln77_fu_663_p3;
wire   [11:0] tmp_169_fu_691_p3;
wire   [11:0] tmp_s_fu_679_p3;
wire   [11:0] zext_ln79_1_fu_687_p1;
wire   [11:0] add_ln80_fu_704_p2;
wire   [0:0] icmp_ln81_fu_841_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 f_fu_162 = 6'd0;
#0 t_fu_166 = 6'd0;
#0 indvar_flatten7_fu_170 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_gesture_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln77_fu_633_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            f_fu_162 <= add_ln78_fu_785_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            f_fu_162 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln77_fu_633_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten7_fu_170 <= add_ln77_1_fu_639_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten7_fu_170 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln77_fu_633_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_166 <= select_ln77_1_fu_671_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_166 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln77_1_reg_911 <= select_ln77_1_fu_671_p3;
        trunc_ln78_reg_926 <= trunc_ln78_fu_715_p1;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_633_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_f_load = 6'd0;
    end else begin
        ap_sig_allocacmp_f_load = f_fu_162;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten7_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten7_load = indvar_flatten7_fu_170;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 6'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_166;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_out_ce0_local = 1'b1;
    end else begin
        conv1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_out_ce1_local = 1'b1;
    end else begin
        conv1_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_10_ce0_local = 1'b1;
    end else begin
        pool1_out_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_10_we0_local = 1'b1;
    end else begin
        pool1_out_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_11_ce0_local = 1'b1;
    end else begin
        pool1_out_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd11) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_11_we0_local = 1'b1;
    end else begin
        pool1_out_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_12_ce0_local = 1'b1;
    end else begin
        pool1_out_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_12_we0_local = 1'b1;
    end else begin
        pool1_out_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_13_ce0_local = 1'b1;
    end else begin
        pool1_out_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd13) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_13_we0_local = 1'b1;
    end else begin
        pool1_out_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_14_ce0_local = 1'b1;
    end else begin
        pool1_out_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_14_we0_local = 1'b1;
    end else begin
        pool1_out_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_15_ce0_local = 1'b1;
    end else begin
        pool1_out_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_15_we0_local = 1'b1;
    end else begin
        pool1_out_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_16_ce0_local = 1'b1;
    end else begin
        pool1_out_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_16_we0_local = 1'b1;
    end else begin
        pool1_out_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_17_ce0_local = 1'b1;
    end else begin
        pool1_out_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd17) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_17_we0_local = 1'b1;
    end else begin
        pool1_out_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_18_ce0_local = 1'b1;
    end else begin
        pool1_out_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd18) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_18_we0_local = 1'b1;
    end else begin
        pool1_out_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_19_ce0_local = 1'b1;
    end else begin
        pool1_out_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd19) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_19_we0_local = 1'b1;
    end else begin
        pool1_out_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_1_ce0_local = 1'b1;
    end else begin
        pool1_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_1_we0_local = 1'b1;
    end else begin
        pool1_out_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_20_ce0_local = 1'b1;
    end else begin
        pool1_out_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd20) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_20_we0_local = 1'b1;
    end else begin
        pool1_out_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_21_ce0_local = 1'b1;
    end else begin
        pool1_out_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd21) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_21_we0_local = 1'b1;
    end else begin
        pool1_out_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_22_ce0_local = 1'b1;
    end else begin
        pool1_out_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd22) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_22_we0_local = 1'b1;
    end else begin
        pool1_out_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_23_ce0_local = 1'b1;
    end else begin
        pool1_out_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd23) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_23_we0_local = 1'b1;
    end else begin
        pool1_out_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_24_ce0_local = 1'b1;
    end else begin
        pool1_out_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd24) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_24_we0_local = 1'b1;
    end else begin
        pool1_out_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_25_ce0_local = 1'b1;
    end else begin
        pool1_out_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd25) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_25_we0_local = 1'b1;
    end else begin
        pool1_out_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_26_ce0_local = 1'b1;
    end else begin
        pool1_out_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd26) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_26_we0_local = 1'b1;
    end else begin
        pool1_out_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_27_ce0_local = 1'b1;
    end else begin
        pool1_out_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd27) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_27_we0_local = 1'b1;
    end else begin
        pool1_out_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_28_ce0_local = 1'b1;
    end else begin
        pool1_out_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd28) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_28_we0_local = 1'b1;
    end else begin
        pool1_out_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_29_ce0_local = 1'b1;
    end else begin
        pool1_out_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd29) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_29_we0_local = 1'b1;
    end else begin
        pool1_out_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_2_ce0_local = 1'b1;
    end else begin
        pool1_out_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_2_we0_local = 1'b1;
    end else begin
        pool1_out_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_30_ce0_local = 1'b1;
    end else begin
        pool1_out_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd30) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_30_we0_local = 1'b1;
    end else begin
        pool1_out_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_31_ce0_local = 1'b1;
    end else begin
        pool1_out_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd31) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_31_we0_local = 1'b1;
    end else begin
        pool1_out_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_3_ce0_local = 1'b1;
    end else begin
        pool1_out_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_3_we0_local = 1'b1;
    end else begin
        pool1_out_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_4_ce0_local = 1'b1;
    end else begin
        pool1_out_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_4_we0_local = 1'b1;
    end else begin
        pool1_out_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_5_ce0_local = 1'b1;
    end else begin
        pool1_out_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_5_we0_local = 1'b1;
    end else begin
        pool1_out_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_6_ce0_local = 1'b1;
    end else begin
        pool1_out_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_6_we0_local = 1'b1;
    end else begin
        pool1_out_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_7_ce0_local = 1'b1;
    end else begin
        pool1_out_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_7_we0_local = 1'b1;
    end else begin
        pool1_out_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_8_ce0_local = 1'b1;
    end else begin
        pool1_out_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_8_we0_local = 1'b1;
    end else begin
        pool1_out_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_9_ce0_local = 1'b1;
    end else begin
        pool1_out_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd9) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_9_we0_local = 1'b1;
    end else begin
        pool1_out_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_ce0_local = 1'b1;
    end else begin
        pool1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln78_reg_926 == 5'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_we0_local = 1'b1;
    end else begin
        pool1_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln77_1_fu_639_p2 = (ap_sig_allocacmp_indvar_flatten7_load + 11'd1);

assign add_ln77_fu_651_p2 = (ap_sig_allocacmp_t_load + 6'd1);

assign add_ln78_fu_785_p2 = (select_ln77_fu_663_p3 + 6'd1);

assign add_ln80_fu_704_p2 = (tmp_s_fu_679_p3 + zext_ln79_1_fu_687_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv1_out_address0 = zext_ln80_fu_710_p1;

assign conv1_out_address1 = zext_ln79_fu_699_p1;

assign conv1_out_ce0 = conv1_out_ce0_local;

assign conv1_out_ce1 = conv1_out_ce1_local;

assign icmp_ln77_fu_633_p2 = ((ap_sig_allocacmp_indvar_flatten7_load == 11'd1600) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_657_p2 = ((ap_sig_allocacmp_f_load == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_841_p2 = (($signed(conv1_out_q1) > $signed(conv1_out_q0)) ? 1'b1 : 1'b0);

assign pool1_out_10_address0 = zext_ln77_fu_806_p1;

assign pool1_out_10_ce0 = pool1_out_10_ce0_local;

assign pool1_out_10_d0 = select_ln81_fu_847_p3;

assign pool1_out_10_we0 = pool1_out_10_we0_local;

assign pool1_out_11_address0 = zext_ln77_fu_806_p1;

assign pool1_out_11_ce0 = pool1_out_11_ce0_local;

assign pool1_out_11_d0 = select_ln81_fu_847_p3;

assign pool1_out_11_we0 = pool1_out_11_we0_local;

assign pool1_out_12_address0 = zext_ln77_fu_806_p1;

assign pool1_out_12_ce0 = pool1_out_12_ce0_local;

assign pool1_out_12_d0 = select_ln81_fu_847_p3;

assign pool1_out_12_we0 = pool1_out_12_we0_local;

assign pool1_out_13_address0 = zext_ln77_fu_806_p1;

assign pool1_out_13_ce0 = pool1_out_13_ce0_local;

assign pool1_out_13_d0 = select_ln81_fu_847_p3;

assign pool1_out_13_we0 = pool1_out_13_we0_local;

assign pool1_out_14_address0 = zext_ln77_fu_806_p1;

assign pool1_out_14_ce0 = pool1_out_14_ce0_local;

assign pool1_out_14_d0 = select_ln81_fu_847_p3;

assign pool1_out_14_we0 = pool1_out_14_we0_local;

assign pool1_out_15_address0 = zext_ln77_fu_806_p1;

assign pool1_out_15_ce0 = pool1_out_15_ce0_local;

assign pool1_out_15_d0 = select_ln81_fu_847_p3;

assign pool1_out_15_we0 = pool1_out_15_we0_local;

assign pool1_out_16_address0 = zext_ln77_fu_806_p1;

assign pool1_out_16_ce0 = pool1_out_16_ce0_local;

assign pool1_out_16_d0 = select_ln81_fu_847_p3;

assign pool1_out_16_we0 = pool1_out_16_we0_local;

assign pool1_out_17_address0 = zext_ln77_fu_806_p1;

assign pool1_out_17_ce0 = pool1_out_17_ce0_local;

assign pool1_out_17_d0 = select_ln81_fu_847_p3;

assign pool1_out_17_we0 = pool1_out_17_we0_local;

assign pool1_out_18_address0 = zext_ln77_fu_806_p1;

assign pool1_out_18_ce0 = pool1_out_18_ce0_local;

assign pool1_out_18_d0 = select_ln81_fu_847_p3;

assign pool1_out_18_we0 = pool1_out_18_we0_local;

assign pool1_out_19_address0 = zext_ln77_fu_806_p1;

assign pool1_out_19_ce0 = pool1_out_19_ce0_local;

assign pool1_out_19_d0 = select_ln81_fu_847_p3;

assign pool1_out_19_we0 = pool1_out_19_we0_local;

assign pool1_out_1_address0 = zext_ln77_fu_806_p1;

assign pool1_out_1_ce0 = pool1_out_1_ce0_local;

assign pool1_out_1_d0 = select_ln81_fu_847_p3;

assign pool1_out_1_we0 = pool1_out_1_we0_local;

assign pool1_out_20_address0 = zext_ln77_fu_806_p1;

assign pool1_out_20_ce0 = pool1_out_20_ce0_local;

assign pool1_out_20_d0 = select_ln81_fu_847_p3;

assign pool1_out_20_we0 = pool1_out_20_we0_local;

assign pool1_out_21_address0 = zext_ln77_fu_806_p1;

assign pool1_out_21_ce0 = pool1_out_21_ce0_local;

assign pool1_out_21_d0 = select_ln81_fu_847_p3;

assign pool1_out_21_we0 = pool1_out_21_we0_local;

assign pool1_out_22_address0 = zext_ln77_fu_806_p1;

assign pool1_out_22_ce0 = pool1_out_22_ce0_local;

assign pool1_out_22_d0 = select_ln81_fu_847_p3;

assign pool1_out_22_we0 = pool1_out_22_we0_local;

assign pool1_out_23_address0 = zext_ln77_fu_806_p1;

assign pool1_out_23_ce0 = pool1_out_23_ce0_local;

assign pool1_out_23_d0 = select_ln81_fu_847_p3;

assign pool1_out_23_we0 = pool1_out_23_we0_local;

assign pool1_out_24_address0 = zext_ln77_fu_806_p1;

assign pool1_out_24_ce0 = pool1_out_24_ce0_local;

assign pool1_out_24_d0 = select_ln81_fu_847_p3;

assign pool1_out_24_we0 = pool1_out_24_we0_local;

assign pool1_out_25_address0 = zext_ln77_fu_806_p1;

assign pool1_out_25_ce0 = pool1_out_25_ce0_local;

assign pool1_out_25_d0 = select_ln81_fu_847_p3;

assign pool1_out_25_we0 = pool1_out_25_we0_local;

assign pool1_out_26_address0 = zext_ln77_fu_806_p1;

assign pool1_out_26_ce0 = pool1_out_26_ce0_local;

assign pool1_out_26_d0 = select_ln81_fu_847_p3;

assign pool1_out_26_we0 = pool1_out_26_we0_local;

assign pool1_out_27_address0 = zext_ln77_fu_806_p1;

assign pool1_out_27_ce0 = pool1_out_27_ce0_local;

assign pool1_out_27_d0 = select_ln81_fu_847_p3;

assign pool1_out_27_we0 = pool1_out_27_we0_local;

assign pool1_out_28_address0 = zext_ln77_fu_806_p1;

assign pool1_out_28_ce0 = pool1_out_28_ce0_local;

assign pool1_out_28_d0 = select_ln81_fu_847_p3;

assign pool1_out_28_we0 = pool1_out_28_we0_local;

assign pool1_out_29_address0 = zext_ln77_fu_806_p1;

assign pool1_out_29_ce0 = pool1_out_29_ce0_local;

assign pool1_out_29_d0 = select_ln81_fu_847_p3;

assign pool1_out_29_we0 = pool1_out_29_we0_local;

assign pool1_out_2_address0 = zext_ln77_fu_806_p1;

assign pool1_out_2_ce0 = pool1_out_2_ce0_local;

assign pool1_out_2_d0 = select_ln81_fu_847_p3;

assign pool1_out_2_we0 = pool1_out_2_we0_local;

assign pool1_out_30_address0 = zext_ln77_fu_806_p1;

assign pool1_out_30_ce0 = pool1_out_30_ce0_local;

assign pool1_out_30_d0 = select_ln81_fu_847_p3;

assign pool1_out_30_we0 = pool1_out_30_we0_local;

assign pool1_out_31_address0 = zext_ln77_fu_806_p1;

assign pool1_out_31_ce0 = pool1_out_31_ce0_local;

assign pool1_out_31_d0 = select_ln81_fu_847_p3;

assign pool1_out_31_we0 = pool1_out_31_we0_local;

assign pool1_out_3_address0 = zext_ln77_fu_806_p1;

assign pool1_out_3_ce0 = pool1_out_3_ce0_local;

assign pool1_out_3_d0 = select_ln81_fu_847_p3;

assign pool1_out_3_we0 = pool1_out_3_we0_local;

assign pool1_out_4_address0 = zext_ln77_fu_806_p1;

assign pool1_out_4_ce0 = pool1_out_4_ce0_local;

assign pool1_out_4_d0 = select_ln81_fu_847_p3;

assign pool1_out_4_we0 = pool1_out_4_we0_local;

assign pool1_out_5_address0 = zext_ln77_fu_806_p1;

assign pool1_out_5_ce0 = pool1_out_5_ce0_local;

assign pool1_out_5_d0 = select_ln81_fu_847_p3;

assign pool1_out_5_we0 = pool1_out_5_we0_local;

assign pool1_out_6_address0 = zext_ln77_fu_806_p1;

assign pool1_out_6_ce0 = pool1_out_6_ce0_local;

assign pool1_out_6_d0 = select_ln81_fu_847_p3;

assign pool1_out_6_we0 = pool1_out_6_we0_local;

assign pool1_out_7_address0 = zext_ln77_fu_806_p1;

assign pool1_out_7_ce0 = pool1_out_7_ce0_local;

assign pool1_out_7_d0 = select_ln81_fu_847_p3;

assign pool1_out_7_we0 = pool1_out_7_we0_local;

assign pool1_out_8_address0 = zext_ln77_fu_806_p1;

assign pool1_out_8_ce0 = pool1_out_8_ce0_local;

assign pool1_out_8_d0 = select_ln81_fu_847_p3;

assign pool1_out_8_we0 = pool1_out_8_we0_local;

assign pool1_out_9_address0 = zext_ln77_fu_806_p1;

assign pool1_out_9_ce0 = pool1_out_9_ce0_local;

assign pool1_out_9_d0 = select_ln81_fu_847_p3;

assign pool1_out_9_we0 = pool1_out_9_we0_local;

assign pool1_out_address0 = zext_ln77_fu_806_p1;

assign pool1_out_ce0 = pool1_out_ce0_local;

assign pool1_out_d0 = select_ln81_fu_847_p3;

assign pool1_out_we0 = pool1_out_we0_local;

assign select_ln77_1_fu_671_p3 = ((icmp_ln78_fu_657_p2[0:0] == 1'b1) ? add_ln77_fu_651_p2 : ap_sig_allocacmp_t_load);

assign select_ln77_fu_663_p3 = ((icmp_ln78_fu_657_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_f_load);

assign select_ln81_fu_847_p3 = ((icmp_ln81_fu_841_p2[0:0] == 1'b1) ? conv1_out_q1 : conv1_out_q0);

assign tmp_169_fu_691_p3 = {{select_ln77_1_fu_671_p3}, {select_ln77_fu_663_p3}};

assign tmp_s_fu_679_p3 = {{select_ln77_1_fu_671_p3}, {6'd32}};

assign trunc_ln78_fu_715_p1 = select_ln77_fu_663_p3[4:0];

assign zext_ln77_fu_806_p1 = select_ln77_1_reg_911;

assign zext_ln79_1_fu_687_p1 = select_ln77_fu_663_p3;

assign zext_ln79_fu_699_p1 = tmp_169_fu_691_p3;

assign zext_ln80_fu_710_p1 = add_ln80_fu_704_p2;

endmodule //cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_78_2
