// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_197_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        logits_address0,
        logits_ce0,
        logits_q0,
        sext_ln198,
        max_v_1_reload,
        exps_address0,
        exps_ce0,
        exps_we0,
        exps_d0,
        sum_7_out,
        sum_7_out_ap_vld,
        grp_fu_724_p_din0,
        grp_fu_724_p_dout0,
        grp_fu_724_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] logits_address0;
output   logits_ce0;
input  [15:0] logits_q0;
input  [15:0] sext_ln198;
input  [15:0] max_v_1_reload;
output  [2:0] exps_address0;
output   exps_ce0;
output   exps_we0;
output  [15:0] exps_d0;
output  [15:0] sum_7_out;
output   sum_7_out_ap_vld;
output  [31:0] grp_fu_724_p_din0;
input  [63:0] grp_fu_724_p_dout0;
output   grp_fu_724_p_ce;

reg ap_idle;
reg sum_7_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln197_fu_203_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [16:0] sext_ln198_cast_fu_186_p1;
reg  signed [16:0] sext_ln198_cast_reg_660;
reg   [0:0] icmp_ln197_reg_665;
reg   [0:0] icmp_ln197_reg_665_pp0_iter1_reg;
reg   [0:0] icmp_ln197_reg_665_pp0_iter2_reg;
reg   [0:0] icmp_ln197_reg_665_pp0_iter3_reg;
reg   [0:0] icmp_ln197_reg_665_pp0_iter4_reg;
reg   [0:0] icmp_ln197_reg_665_pp0_iter5_reg;
reg   [0:0] icmp_ln197_reg_665_pp0_iter6_reg;
reg   [0:0] icmp_ln197_reg_665_pp0_iter7_reg;
reg   [0:0] icmp_ln197_reg_665_pp0_iter8_reg;
reg   [0:0] icmp_ln197_reg_665_pp0_iter9_reg;
wire   [63:0] zext_ln197_fu_215_p1;
reg   [63:0] zext_ln197_reg_669;
reg   [63:0] zext_ln197_reg_669_pp0_iter1_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter2_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter3_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter4_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter5_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter6_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter7_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter8_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter9_reg;
reg   [63:0] zext_ln197_reg_669_pp0_iter10_reg;
wire   [0:0] icmp_ln198_fu_238_p2;
reg   [0:0] icmp_ln198_reg_679;
wire   [0:0] tmp_fu_243_p3;
reg   [0:0] tmp_reg_684;
wire   [15:0] select_ln198_fu_257_p3;
reg   [15:0] select_ln198_reg_689;
wire   [4:0] trunc_ln198_1_fu_277_p1;
reg   [4:0] trunc_ln198_1_reg_694;
wire   [4:0] add_ln198_fu_281_p2;
reg   [4:0] add_ln198_reg_699;
wire   [31:0] grp_fu_180_p2;
wire   [15:0] storemerge4_i_fu_599_p11;
reg   [15:0] storemerge4_i_reg_714;
wire    ap_block_pp0_stage0;
reg   [15:0] sum_7_fu_124;
wire   [15:0] sum_fu_626_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [2:0] i_1_fu_128;
wire   [2:0] add_ln197_fu_209_p2;
reg   [2:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage0_01001;
reg    logits_ce0_local;
reg    exps_we0_local;
reg    exps_ce0_local;
wire   [31:0] grp_fu_180_p1;
wire  signed [15:0] sext_ln198_1_fu_225_p0;
wire  signed [16:0] sext_ln198_1_fu_225_p1;
wire   [16:0] sub_ln198_fu_229_p2;
wire  signed [15:0] icmp_ln198_fu_238_p0;
wire   [15:0] trunc_ln198_fu_234_p1;
wire   [15:0] sub_ln198_1_fu_251_p2;
wire   [16:0] tmp_50_fu_269_p1;
wire   [16:0] tmp_50_fu_269_p3;
wire   [40:0] zext_ln198_1_fu_287_p1;
wire   [40:0] zext_ln198_2_fu_290_p1;
wire   [40:0] shl_ln198_fu_293_p2;
wire   [39:0] lshr_ln3_fu_299_p4;
wire   [0:0] tmp_234_fu_313_p3;
wire   [4:0] sub_ln198_2_fu_329_p2;
wire  signed [7:0] sext_ln198_2_fu_334_p1;
wire   [7:0] select_ln198_1_fu_321_p3;
wire   [7:0] add_ln198_1_fu_338_p2;
wire   [63:0] zext_ln198_4_fu_309_p1;
wire   [8:0] tmp_52_fu_344_p3;
wire   [63:0] pi_assign_fu_351_p5;
wire   [31:0] LD_fu_363_p1;
wire   [31:0] bitcast_ln768_fu_367_p1;
wire   [63:0] bitcast_ln726_17_fu_379_p1;
wire   [10:0] tmp_60_fu_395_p3;
wire   [51:0] trunc_ln198_3_fu_407_p1;
wire   [52:0] zext_ln198_6_cast_fu_411_p3;
wire   [53:0] zext_ln198_6_fu_419_p1;
wire   [0:0] tmp_235_fu_387_p3;
wire   [53:0] sub_ln198_3_fu_423_p2;
wire   [62:0] trunc_ln198_2_fu_383_p1;
wire   [11:0] zext_ln198_3_fu_403_p1;
wire   [11:0] sub_ln198_4_fu_443_p2;
wire   [10:0] trunc_ln198_4_fu_449_p1;
wire   [0:0] icmp_ln198_2_fu_453_p2;
wire   [10:0] add_ln198_2_fu_459_p2;
wire   [10:0] sub_ln198_5_fu_465_p2;
wire   [53:0] select_ln198_2_fu_429_p3;
wire   [10:0] select_ln198_3_fu_471_p3;
wire   [53:0] zext_ln198_5_fu_503_p1;
wire   [53:0] ashr_ln198_fu_507_p2;
wire   [0:0] icmp_ln198_4_fu_489_p2;
wire   [15:0] trunc_ln198_6_fu_513_p1;
wire   [15:0] select_ln198_6_fu_495_p3;
wire   [6:0] tmp_236_fu_525_p4;
wire   [15:0] trunc_ln198_5_fu_485_p1;
wire   [15:0] select_ln198_3cast_fu_541_p1;
wire   [0:0] icmp_ln198_5_fu_535_p2;
wire   [15:0] shl_ln198_1_fu_545_p2;
wire   [0:0] icmp_ln198_1_fu_437_p2;
wire   [0:0] icmp_ln198_3_fu_479_p2;
wire   [0:0] xor_ln198_fu_559_p2;
wire   [0:0] or_ln198_fu_571_p2;
wire   [0:0] xor_ln198_1_fu_577_p2;
wire   [0:0] and_ln198_fu_565_p2;
wire   [0:0] and_ln198_1_fu_583_p2;
wire   [15:0] storemerge4_i_fu_599_p6;
wire   [15:0] storemerge4_i_fu_599_p8;
wire   [15:0] storemerge4_i_fu_599_p9;
wire   [2:0] storemerge4_i_fu_599_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [16:0] tmp_50_fu_269_p0;
wire   [0:0] tmp_50_fu_269_p2;
wire  signed [2:0] storemerge4_i_fu_599_p1;
wire   [2:0] storemerge4_i_fu_599_p3;
wire   [2:0] storemerge4_i_fu_599_p5;
wire   [2:0] storemerge4_i_fu_599_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 sum_7_fu_124 = 16'd0;
#0 i_1_fu_128 = 3'd0;
#0 ap_done_reg = 1'b0;
end

cnn_gesture_top_fexp_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fexp_32ns_32ns_32_8_full_dsp_1_U410(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_180_p1),
    .ce(1'b1),
    .dout(grp_fu_180_p2)
);

cnn_gesture_top_ctlz_17_17_1_1 #(
    .din_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
ctlz_17_17_1_1_U411(
    .din(tmp_50_fu_269_p1),
    .dout(tmp_50_fu_269_p3)
);

(* dissolve_hierarchy = "yes" *) cnn_gesture_top_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U412(
    .din0(16'd0),
    .din1(trunc_ln198_5_fu_485_p1),
    .din2(storemerge4_i_fu_599_p6),
    .din3(storemerge4_i_fu_599_p8),
    .def(storemerge4_i_fu_599_p9),
    .sel(storemerge4_i_fu_599_p10),
    .dout(storemerge4_i_fu_599_p11)
);

cnn_gesture_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln197_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_128 <= add_ln197_fu_209_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_128 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            sum_7_fu_124 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter11 == 1'b1)) begin
            sum_7_fu_124 <= sum_fu_626_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln198_reg_699 <= add_ln198_fu_281_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln197_reg_665 <= icmp_ln197_fu_203_p2;
        icmp_ln197_reg_665_pp0_iter1_reg <= icmp_ln197_reg_665;
        icmp_ln198_reg_679 <= icmp_ln198_fu_238_p2;
        select_ln198_reg_689 <= select_ln198_fu_257_p3;
        sext_ln198_cast_reg_660 <= sext_ln198_cast_fu_186_p1;
        tmp_reg_684 <= sub_ln198_fu_229_p2[32'd16];
        trunc_ln198_1_reg_694 <= trunc_ln198_1_fu_277_p1;
        zext_ln197_reg_669[2 : 0] <= zext_ln197_fu_215_p1[2 : 0];
        zext_ln197_reg_669_pp0_iter1_reg[2 : 0] <= zext_ln197_reg_669[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln197_reg_665_pp0_iter2_reg <= icmp_ln197_reg_665_pp0_iter1_reg;
        icmp_ln197_reg_665_pp0_iter3_reg <= icmp_ln197_reg_665_pp0_iter2_reg;
        icmp_ln197_reg_665_pp0_iter4_reg <= icmp_ln197_reg_665_pp0_iter3_reg;
        icmp_ln197_reg_665_pp0_iter5_reg <= icmp_ln197_reg_665_pp0_iter4_reg;
        icmp_ln197_reg_665_pp0_iter6_reg <= icmp_ln197_reg_665_pp0_iter5_reg;
        icmp_ln197_reg_665_pp0_iter7_reg <= icmp_ln197_reg_665_pp0_iter6_reg;
        icmp_ln197_reg_665_pp0_iter8_reg <= icmp_ln197_reg_665_pp0_iter7_reg;
        icmp_ln197_reg_665_pp0_iter9_reg <= icmp_ln197_reg_665_pp0_iter8_reg;
        storemerge4_i_reg_714 <= storemerge4_i_fu_599_p11;
        zext_ln197_reg_669_pp0_iter10_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter9_reg[2 : 0];
        zext_ln197_reg_669_pp0_iter2_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter1_reg[2 : 0];
        zext_ln197_reg_669_pp0_iter3_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter2_reg[2 : 0];
        zext_ln197_reg_669_pp0_iter4_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter3_reg[2 : 0];
        zext_ln197_reg_669_pp0_iter5_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter4_reg[2 : 0];
        zext_ln197_reg_669_pp0_iter6_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter5_reg[2 : 0];
        zext_ln197_reg_669_pp0_iter7_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter6_reg[2 : 0];
        zext_ln197_reg_669_pp0_iter8_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter7_reg[2 : 0];
        zext_ln197_reg_669_pp0_iter9_reg[2 : 0] <= zext_ln197_reg_669_pp0_iter8_reg[2 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln197_fu_203_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 3'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        exps_ce0_local = 1'b1;
    end else begin
        exps_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        exps_we0_local = 1'b1;
    end else begin
        exps_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        logits_ce0_local = 1'b1;
    end else begin
        logits_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (icmp_ln197_reg_665_pp0_iter9_reg == 1'd1))) begin
        sum_7_out_ap_vld = 1'b1;
    end else begin
        sum_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_fu_363_p1 = pi_assign_fu_351_p5[31:0];

assign add_ln197_fu_209_p2 = (ap_sig_allocacmp_i + 3'd1);

assign add_ln198_1_fu_338_p2 = ($signed(sext_ln198_2_fu_334_p1) + $signed(select_ln198_1_fu_321_p3));

assign add_ln198_2_fu_459_p2 = ($signed(trunc_ln198_4_fu_449_p1) + $signed(11'd2038));

assign add_ln198_fu_281_p2 = (trunc_ln198_1_fu_277_p1 + 5'd8);

assign and_ln198_1_fu_583_p2 = (xor_ln198_1_fu_577_p2 & icmp_ln198_2_fu_453_p2);

assign and_ln198_fu_565_p2 = (xor_ln198_fu_559_p2 & icmp_ln198_3_fu_479_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ashr_ln198_fu_507_p2 = $signed(select_ln198_2_fu_429_p3) >>> zext_ln198_5_fu_503_p1;

assign bitcast_ln726_17_fu_379_p1 = grp_fu_724_p_dout0;

assign bitcast_ln768_fu_367_p1 = LD_fu_363_p1;

assign exps_address0 = zext_ln197_reg_669_pp0_iter10_reg;

assign exps_ce0 = exps_ce0_local;

assign exps_d0 = storemerge4_i_reg_714;

assign exps_we0 = exps_we0_local;

assign grp_fu_180_p1 = ((icmp_ln198_reg_679[0:0] == 1'b1) ? 32'd0 : bitcast_ln768_fu_367_p1);

assign grp_fu_724_p_ce = 1'b1;

assign grp_fu_724_p_din0 = grp_fu_180_p2;

assign icmp_ln197_fu_203_p2 = ((ap_sig_allocacmp_i == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln198_1_fu_437_p2 = ((trunc_ln198_2_fu_383_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln198_2_fu_453_p2 = (($signed(sub_ln198_4_fu_443_p2) > $signed(12'd10)) ? 1'b1 : 1'b0);

assign icmp_ln198_3_fu_479_p2 = ((sub_ln198_4_fu_443_p2 == 12'd10) ? 1'b1 : 1'b0);

assign icmp_ln198_4_fu_489_p2 = ((select_ln198_3_fu_471_p3 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln198_5_fu_535_p2 = ((tmp_236_fu_525_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln198_fu_238_p0 = logits_q0;

assign icmp_ln198_fu_238_p2 = ((icmp_ln198_fu_238_p0 == max_v_1_reload) ? 1'b1 : 1'b0);

assign logits_address0 = zext_ln197_fu_215_p1;

assign logits_ce0 = logits_ce0_local;

assign lshr_ln3_fu_299_p4 = {{shl_ln198_fu_293_p2[40:1]}};

assign or_ln198_fu_571_p2 = (icmp_ln198_3_fu_479_p2 | icmp_ln198_1_fu_437_p2);

assign pi_assign_fu_351_p5 = {{zext_ln198_4_fu_309_p1[63:32]}, {tmp_52_fu_344_p3}, {zext_ln198_4_fu_309_p1[22:0]}};

assign select_ln198_1_fu_321_p3 = ((tmp_234_fu_313_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln198_2_fu_429_p3 = ((tmp_235_fu_387_p3[0:0] == 1'b1) ? sub_ln198_3_fu_423_p2 : zext_ln198_6_fu_419_p1);

assign select_ln198_3_fu_471_p3 = ((icmp_ln198_2_fu_453_p2[0:0] == 1'b1) ? add_ln198_2_fu_459_p2 : sub_ln198_5_fu_465_p2);

assign select_ln198_3cast_fu_541_p1 = select_ln198_3_fu_471_p3;

assign select_ln198_6_fu_495_p3 = ((tmp_235_fu_387_p3[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln198_fu_257_p3 = ((tmp_fu_243_p3[0:0] == 1'b1) ? sub_ln198_1_fu_251_p2 : trunc_ln198_fu_234_p1);

assign sext_ln198_1_fu_225_p0 = logits_q0;

assign sext_ln198_1_fu_225_p1 = sext_ln198_1_fu_225_p0;

assign sext_ln198_2_fu_334_p1 = $signed(sub_ln198_2_fu_329_p2);

assign sext_ln198_cast_fu_186_p1 = $signed(sext_ln198);

assign shl_ln198_1_fu_545_p2 = trunc_ln198_5_fu_485_p1 << select_ln198_3cast_fu_541_p1;

assign shl_ln198_fu_293_p2 = zext_ln198_1_fu_287_p1 << zext_ln198_2_fu_290_p1;

assign storemerge4_i_fu_599_p10 = {{{icmp_ln198_1_fu_437_p2}, {and_ln198_fu_565_p2}}, {and_ln198_1_fu_583_p2}};

assign storemerge4_i_fu_599_p6 = ((icmp_ln198_4_fu_489_p2[0:0] == 1'b1) ? trunc_ln198_6_fu_513_p1 : select_ln198_6_fu_495_p3);

assign storemerge4_i_fu_599_p8 = ((icmp_ln198_5_fu_535_p2[0:0] == 1'b1) ? shl_ln198_1_fu_545_p2 : 16'd0);

assign storemerge4_i_fu_599_p9 = 'bx;

assign sub_ln198_1_fu_251_p2 = (16'd0 - trunc_ln198_fu_234_p1);

assign sub_ln198_2_fu_329_p2 = (5'd7 - trunc_ln198_1_reg_694);

assign sub_ln198_3_fu_423_p2 = (54'd0 - zext_ln198_6_fu_419_p1);

assign sub_ln198_4_fu_443_p2 = (12'd1075 - zext_ln198_3_fu_403_p1);

assign sub_ln198_5_fu_465_p2 = (11'd10 - trunc_ln198_4_fu_449_p1);

assign sub_ln198_fu_229_p2 = ($signed(sext_ln198_1_fu_225_p1) - $signed(sext_ln198_cast_reg_660));

assign sum_7_out = sum_7_fu_124;

assign sum_fu_626_p2 = (storemerge4_i_reg_714 + sum_7_fu_124);

assign tmp_234_fu_313_p3 = shl_ln198_fu_293_p2[32'd25];

assign tmp_235_fu_387_p3 = bitcast_ln726_17_fu_379_p1[32'd63];

assign tmp_236_fu_525_p4 = {{select_ln198_3_fu_471_p3[10:4]}};

assign tmp_50_fu_269_p1 = select_ln198_fu_257_p3;

assign tmp_52_fu_344_p3 = {{tmp_reg_684}, {add_ln198_1_fu_338_p2}};

assign tmp_60_fu_395_p3 = {{bitcast_ln726_17_fu_379_p1[62:52]}};

assign tmp_fu_243_p3 = sub_ln198_fu_229_p2[32'd16];

assign trunc_ln198_1_fu_277_p1 = tmp_50_fu_269_p3[4:0];

assign trunc_ln198_2_fu_383_p1 = bitcast_ln726_17_fu_379_p1[62:0];

assign trunc_ln198_3_fu_407_p1 = bitcast_ln726_17_fu_379_p1[51:0];

assign trunc_ln198_4_fu_449_p1 = sub_ln198_4_fu_443_p2[10:0];

assign trunc_ln198_5_fu_485_p1 = select_ln198_2_fu_429_p3[15:0];

assign trunc_ln198_6_fu_513_p1 = ashr_ln198_fu_507_p2[15:0];

assign trunc_ln198_fu_234_p1 = sub_ln198_fu_229_p2[15:0];

assign xor_ln198_1_fu_577_p2 = (or_ln198_fu_571_p2 ^ 1'd1);

assign xor_ln198_fu_559_p2 = (icmp_ln198_1_fu_437_p2 ^ 1'd1);

assign zext_ln197_fu_215_p1 = ap_sig_allocacmp_i;

assign zext_ln198_1_fu_287_p1 = select_ln198_reg_689;

assign zext_ln198_2_fu_290_p1 = add_ln198_reg_699;

assign zext_ln198_3_fu_403_p1 = tmp_60_fu_395_p3;

assign zext_ln198_4_fu_309_p1 = lshr_ln3_fu_299_p4;

assign zext_ln198_5_fu_503_p1 = select_ln198_3_fu_471_p3;

assign zext_ln198_6_cast_fu_411_p3 = {{1'd1}, {trunc_ln198_3_fu_407_p1}};

assign zext_ln198_6_fu_419_p1 = zext_ln198_6_cast_fu_411_p3;

always @ (posedge ap_clk) begin
    zext_ln197_reg_669[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter1_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter2_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter3_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter4_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter5_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter6_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter7_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter8_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter9_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln197_reg_669_pp0_iter10_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_197_2
