[hls]
relative_roots=C:/Users/Jonathan/Desktop/capstone/ai/vitis_hls/hls_component
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_63_2 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_101_2 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_119_3 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_150_2 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_166_2 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_183_2 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_201_2 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_214_1 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_220_2 
syn.directive.pipeline=cnn_gesture_core/VITIS_LOOP_225_3 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=cnn_gesture_core/VITIS_LOOP_62_1  
syn.directive.loop_flatten=cnn_gesture_core/VITIS_LOOP_100_1  
syn.directive.loop_flatten=cnn_gesture_core/VITIS_LOOP_149_1  
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=cnn_gesture_top/VITIS_LOOP_270_1  


