[hls]
relative_roots=C:/Users/Jonathan/Desktop/capstone/ai/vitis_hls/hls_component
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=tiny_classifier/VITIS_LOOP_70_1 
syn.directive.pipeline=tiny_classifier/VITIS_LOOP_85_4 
syn.directive.pipeline=tiny_classifier/VITIS_LOOP_90_5 
syn.directive.pipeline=tiny_classifier/VITIS_LOOP_33_1 
syn.directive.pipeline=tiny_classifier/VITIS_LOOP_39_2 
syn.directive.pipeline=tiny_classifier/VITIS_LOOP_45_3 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=tiny_classifier/VITIS_LOOP_74_2  


