# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_40_2
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_78_2
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_96_3
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_127_2
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_143_2
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_160_2
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_178_2
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_191_1
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_197_2
set_directive_pipeline cnn_gesture_top/VITIS_LOOP_202_3
# Inferred from Performance Budgeter performance directives
set_directive_loop_flatten cnn_gesture_top/VITIS_LOOP_39_1
set_directive_loop_flatten cnn_gesture_top/VITIS_LOOP_77_1
set_directive_loop_flatten cnn_gesture_top/VITIS_LOOP_126_1
