# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline tiny_classifier/VITIS_LOOP_70_1
set_directive_pipeline tiny_classifier/VITIS_LOOP_85_4
set_directive_pipeline tiny_classifier/VITIS_LOOP_90_5
set_directive_pipeline tiny_classifier/VITIS_LOOP_33_1
set_directive_pipeline tiny_classifier/VITIS_LOOP_39_2
set_directive_pipeline tiny_classifier/VITIS_LOOP_45_3
# Inferred from performance & pipeline pragmas/directives
set_directive_loop_flatten tiny_classifier/VITIS_LOOP_74_2
