set SynModuleInfo {
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_270_1_VITIS_LOOP_271_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_mul_7ns_9ns_15_1_1 RTLNAME cnn_gesture_top_mul_7ns_9ns_15_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_urem_7ns_3ns_2_11_1 RTLNAME cnn_gesture_top_urem_7ns_3ns_2_11_1 BINDTYPE op TYPE urem IMPL auto LATENCY 10 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_sparsemux_9_3_16_1_1 RTLNAME cnn_gesture_top_sparsemux_9_3_16_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
      {MODELNAME cnn_gesture_top_flow_control_loop_pipe_sequential_init RTLNAME cnn_gesture_top_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME cnn_gesture_top_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_mul_64ns_66ns_129_1_1 RTLNAME cnn_gesture_top_mul_64ns_66ns_129_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_ctlz_17_17_1_1 RTLNAME cnn_gesture_top_ctlz_17_17_1_1 BINDTYPE op TYPE ctlz IMPL auto}
      {MODELNAME cnn_gesture_top_mul_6ns_8ns_13_1_1 RTLNAME cnn_gesture_top_mul_6ns_8ns_13_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_mul_8ns_10ns_17_1_1 RTLNAME cnn_gesture_top_mul_8ns_10ns_17_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_mul_9ns_11ns_19_1_1 RTLNAME cnn_gesture_top_mul_9ns_11ns_19_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_mul_10ns_12ns_21_1_1 RTLNAME cnn_gesture_top_mul_10ns_12ns_21_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_sparsemux_39_5_32_1_1 RTLNAME cnn_gesture_top_sparsemux_39_5_32_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME cnn_gesture_top_sparsemux_7_2_16_1_1 RTLNAME cnn_gesture_top_sparsemux_7_2_16_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
      {MODELNAME cnn_gesture_top_mul_16s_16s_26_1_1 RTLNAME cnn_gesture_top_mul_16s_16s_26_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_sdiv_27ns_16s_16_31_1 RTLNAME cnn_gesture_top_sdiv_27ns_16s_16_31_1 BINDTYPE op TYPE sdiv IMPL auto LATENCY 30 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_mac_muladd_16s_16s_26s_26_4_1 RTLNAME cnn_gesture_top_mac_muladd_16s_16s_26s_26_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_bkb RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_bkb BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_cud RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_cud BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_dEe RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_dEe BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_eOg RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_eOg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_fYi RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_fYi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_g8j RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_g8j BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_hbi RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_hbi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_ibs RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_ibs BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_jbC RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_jbC BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_kbM RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_kbM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_lbW RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_lbW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_mb6 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_mb6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_ncg RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_ncg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_ocq RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_ocq BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_pcA RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_pcA BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_qcK RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_qcK BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_rcU RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_rcU BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_sc4 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_sc4 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_tde RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_p_ZL14conv1d_param_tde BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_conv1d_param_1_ROM_udo RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_conv1d_param_1_ROM_udo BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_batch_normalizationvdy RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_batch_normalizationvdy BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_batch_normalizationwdI RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_batch_normalizationwdI BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_batch_normalizationxdS RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_batch_normalizationxdS BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_batch_normalizationyd2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_62_1_VITIS_LOOP_63_2_batch_normalizationyd2 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_2 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_100_1_VITIS_LOOP_101_2}
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3
    SUBMODULES {
      {MODELNAME cnn_gesture_top_urem_11ns_7ns_6_15_1 RTLNAME cnn_gesture_top_urem_11ns_7ns_6_15_1 BINDTYPE op TYPE urem IMPL auto LATENCY 14 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_mul_13ns_15ns_27_1_1 RTLNAME cnn_gesture_top_mul_13ns_15ns_27_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_sparsemux_67_6_32_1_1 RTLNAME cnn_gesture_top_sparsemux_67_6_32_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME cnn_gesture_top_mul_16s_16s_32_1_1 RTLNAME cnn_gesture_top_mul_16s_16s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_am_addmul_11ns_12ns_14ns_27_4_1 RTLNAME cnn_gesture_top_am_addmul_11ns_12ns_14ns_27_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME cnn_gesture_top_mac_muladd_16s_16s_32s_32_4_1 RTLNAME cnn_gesture_top_mac_muladd_16s_16s_32s_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_zec RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_zec BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Aem RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Aem BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Bew RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Bew BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_CeG RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_CeG BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_DeQ RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_DeQ BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Ee0 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Ee0 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Ffa RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Ffa BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Gfk RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Gfk BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Hfu RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Hfu BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_IfE RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_IfE BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_JfO RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_JfO BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_KfY RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_KfY BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Lf8 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Lf8 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Mgi RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Mgi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Ngs RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Ngs BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_OgC RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_OgC BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_PgM RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_PgM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_QgW RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_QgW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Rg6 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Rg6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Shg RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Shg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Thq RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Thq BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_UhA RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_UhA BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_VhK RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_VhK BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_WhU RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_WhU BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Xh4 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Xh4 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Yie RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Yie BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Zio RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_Zio BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_0iy RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_0iy BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_1iI RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_1iI BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_2iS RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_2iS BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_3i2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_3i2 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_4jc RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_4jc BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_5jm RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_5jm BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_6jw RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_6jw BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_7jG RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_7jG BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_8jQ RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_8jQ BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_9j0 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_9j0 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_bak RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_115_1_VITIS_LOOP_116_2_VITIS_LOOP_119_3_bak BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_149_1_VITIS_LOOP_150_2 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_149_1_VITIS_LOOP_150_2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_149_1_VITIS_LOOP_150_2}
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2}
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_183_2 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_183_2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_183_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_183_2_dense_param_0_ROM_AUTO_1R RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_183_2_dense_param_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_201_2 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_201_2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_201_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_mac_muladd_16s_15ns_32s_32_4_1 RTLNAME cnn_gesture_top_mac_muladd_16s_15ns_32s_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_201_2_dense_1_param_0_ROM_AUTO_1R RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_201_2_dense_1_param_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_214_1 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_214_1 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_214_1}
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_220_2 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_220_2 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_220_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME cnn_gesture_top_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_core_Pipeline_VITIS_LOOP_225_3 MODELNAME cnn_gesture_core_Pipeline_VITIS_LOOP_225_3 RTLNAME cnn_gesture_top_cnn_gesture_core_Pipeline_VITIS_LOOP_225_3
    SUBMODULES {
      {MODELNAME cnn_gesture_top_sdiv_26ns_16s_16_30_1 RTLNAME cnn_gesture_top_sdiv_26ns_16s_16_30_1 BINDTYPE op TYPE sdiv IMPL auto LATENCY 29 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_core MODELNAME cnn_gesture_core RTLNAME cnn_gesture_top_cnn_gesture_core
    SUBMODULES {
      {MODELNAME cnn_gesture_top_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME cnn_gesture_top_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_dense_param_1_ROM_AUTO_1R RTLNAME cnn_gesture_top_cnn_gesture_core_dense_param_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_dense_1_param_1_ROM_AUTO_1R RTLNAME cnn_gesture_top_cnn_gesture_core_dense_1_param_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_exps_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_cnn_gesture_core_exps_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_conv1_out_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_cnn_gesture_core_conv1_out_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_pool1_out_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_cnn_gesture_core_pool1_out_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_pool2_out_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_cnn_gesture_core_pool2_out_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_core_fc1_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_cnn_gesture_core_fc1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_281_3 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_281_3 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_281_3
    SUBMODULES {
      {MODELNAME cnn_gesture_top_ctlz_16_16_1_1 RTLNAME cnn_gesture_top_ctlz_16_16_1_1 BINDTYPE op TYPE ctlz IMPL auto}
    }
  }
  {SRCNAME cnn_gesture_top MODELNAME cnn_gesture_top RTLNAME cnn_gesture_top IS_TOP 1
    SUBMODULES {
      {MODELNAME cnn_gesture_top_fpext_32ns_64_2_no_dsp_1 RTLNAME cnn_gesture_top_fpext_32ns_64_2_no_dsp_1 BINDTYPE op TYPE fpext IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_input_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_input_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_output_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_output_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_CTRL_s_axi RTLNAME cnn_gesture_top_CTRL_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME cnn_gesture_top_regslice_both RTLNAME cnn_gesture_top_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
}
