set SynModuleInfo {
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_sparsemux_9_3_16_1_1 RTLNAME cnn_gesture_top_sparsemux_9_3_16_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
      {MODELNAME cnn_gesture_top_ctlz_17_17_1_1 RTLNAME cnn_gesture_top_ctlz_17_17_1_1 BINDTYPE op TYPE ctlz IMPL auto}
      {MODELNAME cnn_gesture_top_mul_16s_16s_26_1_1 RTLNAME cnn_gesture_top_mul_16s_16s_26_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_sdiv_27ns_16s_16_31_1 RTLNAME cnn_gesture_top_sdiv_27ns_16s_16_31_1 BINDTYPE op TYPE sdiv IMPL auto LATENCY 30 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_mac_muladd_16s_16s_26s_26_4_1 RTLNAME cnn_gesture_top_mac_muladd_16s_16s_26s_26_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_p_ZL14conv1d_param_0bkb RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_p_ZL14conv1d_param_0bkb BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_p_ZL14conv1d_param_0cud RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_p_ZL14conv1d_param_0cud BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_conv1d_param_1_ROM_AdEe RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_conv1d_param_1_ROM_AdEe BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_eOg RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_eOg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_fYi RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_fYi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_g8j RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_g8j BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_hbi RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_hbi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_flow_control_loop_pipe_sequential_init RTLNAME cnn_gesture_top_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME cnn_gesture_top_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_78_2 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_78_2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_77_1_VITIS_LOOP_78_2}
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3
    SUBMODULES {
      {MODELNAME cnn_gesture_top_urem_11ns_7ns_6_15_1 RTLNAME cnn_gesture_top_urem_11ns_7ns_6_15_1 BINDTYPE op TYPE urem IMPL auto LATENCY 14 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_mul_13ns_15ns_27_1_1 RTLNAME cnn_gesture_top_mul_13ns_15ns_27_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_sparsemux_67_6_32_1_1 RTLNAME cnn_gesture_top_sparsemux_67_6_32_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME cnn_gesture_top_mul_16s_16s_32_1_1 RTLNAME cnn_gesture_top_mul_16s_16s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_am_addmul_11ns_12ns_14ns_27_4_1 RTLNAME cnn_gesture_top_am_addmul_11ns_12ns_14ns_27_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME cnn_gesture_top_mac_muladd_16s_16s_32s_32_4_1 RTLNAME cnn_gesture_top_mac_muladd_16s_16s_32s_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLibs RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLibs BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLjbC RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLjbC BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLkbM RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLkbM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLlbW RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLlbW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLmb6 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLmb6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLncg RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLncg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLocq RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLocq BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLpcA RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLpcA BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLqcK RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLqcK BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLrcU RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLrcU BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLsc4 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLsc4 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLtde RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLtde BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLudo RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLudo BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLvdy RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLvdy BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLwdI RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLwdI BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLxdS RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLxdS BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLyd2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLyd2 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLzec RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLzec BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLAem RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLAem BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLBew RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLBew BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLCeG RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLCeG BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLDeQ RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLDeQ BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLEe0 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLEe0 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLFfa RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLFfa BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLGfk RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLGfk BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLHfu RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLHfu BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLIfE RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLIfE BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLJfO RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLJfO BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLKfY RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLKfY BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLLf8 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLLf8 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLMgi RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLMgi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLNgs RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLNgs BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLOgC RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_p_ZLOgC BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_convPgM RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_convPgM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_batcQgW RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_batcQgW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_batcRg6 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_batcRg6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_batcShg RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_batcShg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_batcThq RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_92_1_VITIS_LOOP_93_2_VITIS_LOOP_96_3_batcThq BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_126_1_VITIS_LOOP_127_2 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_126_1_VITIS_LOOP_127_2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_126_1_VITIS_LOOP_127_2}
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_142_1_VITIS_LOOP_143_2 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_142_1_VITIS_LOOP_143_2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_142_1_VITIS_LOOP_143_2}
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_160_2 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_160_2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_160_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_160_2_dense_param_0_ROM_AUTO_1R RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_160_2_dense_param_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_178_2 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_178_2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_178_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_mac_muladd_16s_15ns_32s_32_4_1 RTLNAME cnn_gesture_top_mac_muladd_16s_15ns_32s_32_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_178_2_dense_1_param_0_ROM_AUTO_1R RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_178_2_dense_1_param_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_191_1 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_191_1 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_191_1}
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_197_2 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_197_2 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_197_2
    SUBMODULES {
      {MODELNAME cnn_gesture_top_fexp_32ns_32ns_32_8_full_dsp_1 RTLNAME cnn_gesture_top_fexp_32ns_32ns_32_8_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 7 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_top_Pipeline_VITIS_LOOP_202_3 MODELNAME cnn_gesture_top_Pipeline_VITIS_LOOP_202_3 RTLNAME cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_202_3
    SUBMODULES {
      {MODELNAME cnn_gesture_top_sdiv_26ns_16s_16_30_1 RTLNAME cnn_gesture_top_sdiv_26ns_16s_16_30_1 BINDTYPE op TYPE sdiv IMPL auto LATENCY 29 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME cnn_gesture_top MODELNAME cnn_gesture_top RTLNAME cnn_gesture_top IS_TOP 1
    SUBMODULES {
      {MODELNAME cnn_gesture_top_fpext_32ns_64_2_no_dsp_1 RTLNAME cnn_gesture_top_fpext_32ns_64_2_no_dsp_1 BINDTYPE op TYPE fpext IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME cnn_gesture_top_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_dense_param_1_ROM_AUTO_1R RTLNAME cnn_gesture_top_dense_param_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_dense_1_param_1_ROM_AUTO_1R RTLNAME cnn_gesture_top_dense_1_param_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_exps_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_exps_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_conv1_out_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_conv1_out_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_pool1_out_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_pool1_out_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_pool2_out_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_pool2_out_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME cnn_gesture_top_fc1_RAM_AUTO_1R1W RTLNAME cnn_gesture_top_fc1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
