

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "41", "42", "43", "44", "45", "46", "47", "48", "49"],
		"CDFG" : "cnn_gesture_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "737", "EstimateLatencyMax" : "737",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "input_stream_V_data_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "input_stream_V_keep_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "input_stream_V_strb_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "input_stream_V_last_V", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "output_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream",
				"BlockSignal" : [
					{"Name" : "output_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "output_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream"},
			{"Name" : "output_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream"},
			{"Name" : "output_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "output_stream"},
			{"Name" : "B", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "B", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "tiny_classifier_stream_axis_0_float_W_5", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "tiny_classifier_stream_axis_0_float_W_4", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "tiny_classifier_stream_axis_0_float_W_3", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "tiny_classifier_stream_axis_0_float_W_2", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "tiny_classifier_stream_axis_0_float_W_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_tiny_classifier_fu_126", "Port" : "tiny_classifier_stream_axis_0_float_W", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_112_1", "PipelineType" : "pipeline",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "PreState" : ["ap_ST_fsm_state3"], "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "PostState" : ["ap_ST_fsm_state7"]}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.output_probs_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126", "Parent" : "0", "Child" : ["3", "4", "5", "8", "11", "30", "32", "35", "37", "38", "39", "40"],
		"CDFG" : "tiny_classifier",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "726", "EstimateLatencyMax" : "726",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_149", "Port" : "input_stream_V_data_V", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "input_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_149", "Port" : "input_stream_V_keep_V", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "input_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_149", "Port" : "input_stream_V_strb_V", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "input_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_149", "Port" : "input_stream_V_last_V", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "output_probs", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_45_3_fu_223", "Port" : "output_probs", "Inst_start_state" : "22", "Inst_end_state" : "23"}]},
			{"Name" : "B", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183", "Port" : "B", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183", "Port" : "tiny_classifier_stream_axis_0_float_W_5", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183", "Port" : "tiny_classifier_stream_axis_0_float_W_4", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183", "Port" : "tiny_classifier_stream_axis_0_float_W_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183", "Port" : "tiny_classifier_stream_axis_0_float_W_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183", "Port" : "tiny_classifier_stream_axis_0_float_W_1", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "tiny_classifier_stream_axis_0_float_W", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183", "Port" : "tiny_classifier_stream_axis_0_float_W", "Inst_start_state" : "5", "Inst_end_state" : "6"}]}]},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.exps_U", "Parent" : "2"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.logits_U", "Parent" : "2"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_149", "Parent" : "2", "Child" : ["6", "7"],
		"CDFG" : "tiny_classifier_Pipeline_VITIS_LOOP_74_2_VITIS_LOOP_75_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "605", "EstimateLatencyMax" : "605",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream",
				"BlockSignal" : [
					{"Name" : "input_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "input_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream"},
			{"Name" : "input_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream"},
			{"Name" : "input_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "input_stream"},
			{"Name" : "feature_sum_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "feature_sum_1_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "feature_sum_2_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "feature_sum_3_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "feature_sum_4_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "feature_sum_5_load_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_2_VITIS_LOOP_75_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "6", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_149.sparsemux_13_3_32_1_1_U2", "Parent" : "5"},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_149.flow_control_loop_pipe_sequential_init_U", "Parent" : "5"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_85_4_fu_167", "Parent" : "2", "Child" : ["9", "10"],
		"CDFG" : "tiny_classifier_Pipeline_VITIS_LOOP_85_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "feature_sum_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "feature_sum_1_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "feature_sum_2_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "feature_sum_3_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "feature_sum_4_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "feature_sum_5_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_52547_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_42343_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_32139_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_21935_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_11731_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_01527_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_85_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "9", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_85_4_fu_167.sparsemux_13_3_32_1_1_U15", "Parent" : "8"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_85_4_fu_167.flow_control_loop_pipe_sequential_init_U", "Parent" : "8"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183", "Parent" : "2", "Child" : ["12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"],
		"CDFG" : "tiny_classifier_Pipeline_VITIS_LOOP_90_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "35", "EstimateLatencyMax" : "35",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "mux_case_01527_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_11731_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_21935_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_32139_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_42343_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_52547_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "logits", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "B", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "tiny_classifier_stream_axis_0_float_W_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "tiny_classifier_stream_axis_0_float_W", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_90_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter28", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter28", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.B_U", "Parent" : "11"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.tiny_classifier_stream_axis_0_float_W_5_U", "Parent" : "11"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.tiny_classifier_stream_axis_0_float_W_4_U", "Parent" : "11"},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.tiny_classifier_stream_axis_0_float_W_3_U", "Parent" : "11"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.tiny_classifier_stream_axis_0_float_W_2_U", "Parent" : "11"},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.tiny_classifier_stream_axis_0_float_W_1_U", "Parent" : "11"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.tiny_classifier_stream_axis_0_float_W_U", "Parent" : "11"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fadd_32ns_32ns_32_4_full_dsp_1_U29", "Parent" : "11"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fadd_32ns_32ns_32_4_full_dsp_1_U30", "Parent" : "11"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fadd_32ns_32ns_32_4_full_dsp_1_U31", "Parent" : "11"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fadd_32ns_32ns_32_4_full_dsp_1_U32", "Parent" : "11"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fadd_32ns_32ns_32_4_full_dsp_1_U33", "Parent" : "11"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fmul_32ns_32ns_32_3_max_dsp_1_U35", "Parent" : "11"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fmul_32ns_32ns_32_3_max_dsp_1_U36", "Parent" : "11"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fmul_32ns_32ns_32_3_max_dsp_1_U37", "Parent" : "11"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fmul_32ns_32ns_32_3_max_dsp_1_U38", "Parent" : "11"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.fmul_32ns_32ns_32_3_max_dsp_1_U39", "Parent" : "11"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_90_5_fu_183.flow_control_loop_pipe_sequential_init_U", "Parent" : "11"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_33_1_fu_208", "Parent" : "2", "Child" : ["31"],
		"CDFG" : "tiny_classifier_Pipeline_VITIS_LOOP_33_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "8", "EstimateLatencyMax" : "8",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "max_v", "Type" : "None", "Direction" : "I"},
			{"Name" : "logits", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "max_v_1_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_33_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "31", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_33_1_fu_208.flow_control_loop_pipe_sequential_init_U", "Parent" : "30"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_39_2_fu_215", "Parent" : "2", "Child" : ["33", "34"],
		"CDFG" : "tiny_classifier_Pipeline_VITIS_LOOP_39_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "logits", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "max_v_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "exps", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "sum_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_39_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_39_2_fu_215.fexp_32ns_32ns_32_8_full_dsp_1_U60", "Parent" : "32"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_39_2_fu_215.flow_control_loop_pipe_sequential_init_U", "Parent" : "32"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_45_3_fu_223", "Parent" : "2", "Child" : ["36"],
		"CDFG" : "tiny_classifier_Pipeline_VITIS_LOOP_45_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "12", "EstimateLatencyMax" : "12",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "exps", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "inv", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_probs", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_45_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.grp_tiny_classifier_Pipeline_VITIS_LOOP_45_3_fu_223.flow_control_loop_pipe_sequential_init_U", "Parent" : "35"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.fdiv_32ns_32ns_32_9_no_dsp_1_U70", "Parent" : "2"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.fcmp_32ns_32ns_1_2_no_dsp_1_U71", "Parent" : "2"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.faddfsub_32ns_32ns_32_4_full_dsp_1_U72", "Parent" : "2"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_tiny_classifier_fu_126.fmul_32ns_32ns_32_3_max_dsp_1_U73", "Parent" : "2"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U", "Parent" : "0"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "44", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "45", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_last_V_U", "Parent" : "0"},
	{"ID" : "46", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "47", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "48", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "49", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_last_V_U", "Parent" : "0"}]}
