#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("input_0_address0", 9, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("input_0_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("input_0_q0", 16, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("input_0_address1", 9, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("input_0_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("input_0_q1", 16, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("input_1_address0", 9, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("input_1_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("input_1_q0", 16, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("input_1_address1", 9, hls_out, 1, "ap_memory", "MemPortADDR2", 1),
	Port_Property("input_1_ce1", 1, hls_out, 1, "ap_memory", "MemPortCE2", 1),
	Port_Property("input_1_q1", 16, hls_in, 1, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("output_0", 16, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("output_0_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("output_1", 16, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("output_1_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("output_2", 16, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("output_2_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("output_3", 16, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("output_3_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("output_4", 16, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("output_4_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("output_5", 16, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("output_5_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "cnn_gesture_top";
