-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_126_1_VITIS_LOOP_127_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv2_out_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv2_out_ce0 : OUT STD_LOGIC;
    conv2_out_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    conv2_out_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv2_out_ce1 : OUT STD_LOGIC;
    conv2_out_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    pool2_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    pool2_out_ce0 : OUT STD_LOGIC;
    pool2_out_we0 : OUT STD_LOGIC;
    pool2_out_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_126_1_VITIS_LOOP_127_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_640 : STD_LOGIC_VECTOR (10 downto 0) := "11001000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln126_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln130_fu_208_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln130_reg_288 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln128_fu_192_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln129_fu_203_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln130_fu_235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal f_fu_46 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln127_fu_214_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_f_load : STD_LOGIC_VECTOR (6 downto 0);
    signal t_fu_50 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln126_1_fu_152_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_t_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten37_fu_54 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln126_1_fu_120_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten37_load : STD_LOGIC_VECTOR (10 downto 0);
    signal conv2_out_ce1_local : STD_LOGIC;
    signal conv2_out_ce0_local : STD_LOGIC;
    signal pool2_out_we0_local : STD_LOGIC;
    signal select_ln130_fu_245_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pool2_out_ce0_local : STD_LOGIC;
    signal icmp_ln127_fu_138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln126_fu_132_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln126_fu_144_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_171_fu_184_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_170_fu_168_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln128_2_fu_180_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln129_fu_197_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_160_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln128_1_fu_176_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln130_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_gesture_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_gesture_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    f_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln126_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    f_fu_46 <= add_ln127_fu_214_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    f_fu_46 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten37_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln126_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten37_fu_54 <= add_ln126_1_fu_120_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten37_fu_54 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    t_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln126_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    t_fu_50 <= select_ln126_1_fu_152_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_50 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln130_reg_288 <= add_ln130_fu_208_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln126_1_fu_120_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten37_load) + unsigned(ap_const_lv11_1));
    add_ln126_fu_132_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_load) + unsigned(ap_const_lv5_1));
    add_ln127_fu_214_p2 <= std_logic_vector(unsigned(select_ln126_fu_144_p3) + unsigned(ap_const_lv7_1));
    add_ln129_fu_197_p2 <= std_logic_vector(unsigned(tmp_170_fu_168_p3) + unsigned(zext_ln128_2_fu_180_p1));
    add_ln130_fu_208_p2 <= std_logic_vector(unsigned(tmp_s_fu_160_p3) + unsigned(zext_ln128_1_fu_176_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln126_fu_114_p2)
    begin
        if (((icmp_ln126_fu_114_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_f_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, f_fu_46, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_f_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_f_load <= f_fu_46;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten37_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten37_fu_54)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten37_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten37_load <= indvar_flatten37_fu_54;
        end if; 
    end process;


    ap_sig_allocacmp_t_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, t_fu_50)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_t_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_t_load <= t_fu_50;
        end if; 
    end process;

    conv2_out_address0 <= zext_ln129_fu_203_p1(12 - 1 downto 0);
    conv2_out_address1 <= zext_ln128_fu_192_p1(12 - 1 downto 0);
    conv2_out_ce0 <= conv2_out_ce0_local;

    conv2_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_ce1 <= conv2_out_ce1_local;

    conv2_out_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_ce1_local <= ap_const_logic_1;
        else 
            conv2_out_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln126_fu_114_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten37_load = ap_const_lv11_640) else "0";
    icmp_ln127_fu_138_p2 <= "1" when (ap_sig_allocacmp_f_load = ap_const_lv7_40) else "0";
    icmp_ln130_fu_239_p2 <= "1" when (signed(conv2_out_q1) > signed(conv2_out_q0)) else "0";
    pool2_out_address0 <= zext_ln130_fu_235_p1(11 - 1 downto 0);
    pool2_out_ce0 <= pool2_out_ce0_local;

    pool2_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pool2_out_ce0_local <= ap_const_logic_1;
        else 
            pool2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_d0 <= select_ln130_fu_245_p3;
    pool2_out_we0 <= pool2_out_we0_local;

    pool2_out_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pool2_out_we0_local <= ap_const_logic_1;
        else 
            pool2_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln126_1_fu_152_p3 <= 
        add_ln126_fu_132_p2 when (icmp_ln127_fu_138_p2(0) = '1') else 
        ap_sig_allocacmp_t_load;
    select_ln126_fu_144_p3 <= 
        ap_const_lv7_0 when (icmp_ln127_fu_138_p2(0) = '1') else 
        ap_sig_allocacmp_f_load;
    select_ln130_fu_245_p3 <= 
        conv2_out_q1 when (icmp_ln130_fu_239_p2(0) = '1') else 
        conv2_out_q0;
    tmp_170_fu_168_p3 <= (select_ln126_1_fu_152_p3 & ap_const_lv7_40);
    tmp_171_fu_184_p3 <= (select_ln126_1_fu_152_p3 & select_ln126_fu_144_p3);
    tmp_s_fu_160_p3 <= (select_ln126_1_fu_152_p3 & ap_const_lv6_0);
    zext_ln128_1_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln126_fu_144_p3),11));
    zext_ln128_2_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln126_fu_144_p3),12));
    zext_ln128_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_171_fu_184_p3),64));
    zext_ln129_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln129_fu_197_p2),64));
    zext_ln130_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln130_reg_288),64));
end behav;
