-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_hbi is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_hbi is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101000000001100010101111011", 1 => "00111101110000111100011100101110", 2 => "00111011111011111111001110001000", 3 => "00111100110110111011111101001101", 
    4 => "00111100101111010101111101000010", 5 => "00111100001001101011011000001011", 6 => "00111011111101101010011111010000", 7 => "00111100100101010010111110001111", 
    8 => "00111101001001000111110001001111", 9 => "00111100111000110100001001001110", 10 => "00111100100011000110100101100010", 11 => "00111100000001110011110000100110", 
    12 => "00111100011101101111101010000000", 13 => "00111100110100100010110001100101", 14 => "00111100001110111101100001011010", 15 => "00111100101111110000111111011100", 
    16 => "00111101000101100100111010001110", 17 => "00111100101101110000100010000010", 18 => "00111100100110001100110111100110", 19 => "00111011101010001111011000000000", 
    20 => "00111100011000001011100111110010", 21 => "00111100111011110100101101010011", 22 => "00111100100111011111101101011010", 23 => "00111100000100001101110000100101", 
    24 => "00111100110101101011011000101010", 25 => "00111100001000110110011111100101", 26 => "00111100001011110000110110010110", 27 => "00111100100100011101111101101010", 
    28 => "00111100001011110111010101110100", 29 => "00111100100000011010010000010001", 30 => "00111100010001011001101000010110", 31 => "00111100000111001011111111111011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

