-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_eOg is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cnn_gesture_top_cnn_gesture_top_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_batch_normalization_eOg is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111111100000010101101100001001", 1 => "00111111011111110001100101100101", 2 => "00111111100000001001011010011000", 3 => "00111111100000001011110100100100", 
    4 => "00111111011111101011011111001110", 5 => "00111111011111100111111110010011", 6 => "00111111011111000001111011100110", 7 => "00111111011111100110101011110011", 
    8 => "00111111100000000110100110010110", 9 => "00111111100000100100100011000101", 10 => "00111111100000011110101110000001", 11 => "00111111100000001010011101011111", 
    12 => "00111111100000001011111000011011", 13 => "00111111011111001100000110110110", 14 => "00111111100000000100101111011010", 15 => "00111111100000101000100100010011", 
    16 => "00111111100000011010111001100100", 17 => "00111111011111011000110111101000", 18 => "00111111100000110001110110001111", 19 => "00111111011111101000011111001011", 
    20 => "00111111011110001010100000000100", 21 => "00111111011111110101100100101101", 22 => "00111111100000111101110001010010", 23 => "00111111011110110111111111111011", 
    24 => "00111111100000100110011001110100", 25 => "00111111011111100000010110001000", 26 => "00111111011110100100111000010000", 27 => "00111111100000010111010000111100", 
    28 => "00111111100000001111111111010001", 29 => "00111111100000010100000001100110", 30 => "00111111011111011011100110100000", 31 => "00111111011110001111111001100111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

